### PR TITLE
avoid stale parameter events in content filter tests.

### LINKED ISSUE #3065: rclcpp.TestNode.ConfigureNodesFilterAndCheckAddParameterEventCallback failure
see https://github.com/ros2/rclcpp/issues/3065#issue-3945966584

spins off from https://github.com/ros2/rclpy/issues/1609

```console
root@tomoyafujita-B760M-Pro-RS-D4:~/ros2_ws/colcon_ws# export RMW_IMPLEMENTATION=rmw_connextdds
root@tomoyafujita-B760M-Pro-RS-D4:~/ros2_ws/colcon_ws# colcon test --event-handlers console_direct+ --packages-select rclcpp --ctest-args -R test_parameter_event_handler
Starting >>> rclcpp  
UpdateCTestConfiguration  from :/root/ros2_ws/colcon_ws/build/rclcpp/CTestConfiguration.ini
Parse Config file:/root/ros2_ws/colcon_ws/build/rclcpp/CTestConfiguration.ini
   Site: tomoyafujita-B760M-Pro-RS-D4
...
60: /root/ros2_ws/colcon_ws/src/ros2/rclcpp/rclcpp/test/rclcpp/test_parameter_event_handler.cpp:515: Failure
60: Expected equality of these values:
60:   received_from_remote_node1
60:     Which is: 1
60:   false
60: 
60: [  FAILED  ] TestNode.ConfigureNodesFilterAndCheckAddParameterEventCallback (1406 ms)
60: [ RUN      ] TestNode.ConfigureNodesFilterAndCheckAddParameterCallback
60: RTI Connext DDS Non-commercial license is for academic, research, evaluation and personal use only. USE FOR COMMERCIAL PURPOSES IS PROHIBITED. See RTI_LICENSE.TXT for terms. Download free tools at rti.com/ncl. License issued to Non-Commercial User license@rti.com For non-production use only.
60: Expires on 00-jan-00
60: Please contact support@rti.com with any questions or comments.
60: /root/ros2_ws/colcon_ws/src/ros2/rclcpp/rclcpp/test/rclcpp/test_parameter_event_handler.cpp:618: Failure
60: Expected equality of these values:
60:   received_from_remote_node2
60:     Which is: 0
60:   true
60: 
60: [  FAILED  ] TestNode.ConfigureNodesFilterAndCheckAddParameterCallback (1508 ms)
...
```

this issue is generated by https://github.com/ros2/rclcpp/pull/2971

- `rmw_fastrtps` does not have this problem. all tests pass with content filtering as expected.

### PR DESCRIPTION
**Pull request by fujitatomoya**
## Description

Fixes #3065 

### Is this user-facing behavior change?

No

### Did you use Generative AI?

No

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
@Barry-Xu-2018 can you review this? i confirmed that this passes for both connextdds and fastdds.

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclcpp#3085
Gist: https://gist.githubusercontent.com/fujitatomoya/e5a4f3d4bd65e848efdb903c0ad05227/raw/251145d0223fb1dadd5da5db5c2179e2e3a5b57b/ros2.repos
BUILD args:  --packages-up-to rclcpp
TEST args:  --packages-select rclcpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/18330
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/27835/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20849/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/7698/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26818/)

File: rclcpp/test/rclcpp/test_parameter_event_handler.cpp [hunk 1]
```diff
@@ -565,29 +594,37 @@ TEST_F(TestNode, ConfigureNodesFilterAndCheckAddParameterCallback)
...
-    remote_node2_param_name, cb_remote_node2, remote_node_name2);
+  // Note: add_parameter_callback internally uses get_parameter_from_event, which
+  // searches both new_parameters and changed_parameters. This means a queued
+  // declare_parameter event (new_parameters) could trigger the parameter callback
+  // before the content filter takes effect — bypassing the filter on RMW
+  // implementations that don't retroactively purge queued messages.
+  // To make this test deterministic, we use an event-level callback that only
+  // inspects changed_parameters for the assertion flags, rather than relying on
+  // parameter-level callbacks which cannot distinguish new vs changed.
+  auto event_handler = param_handler->add_parameter_event_callback(cb_changed_event);
```
Comment (Barry-Xu-2018) [inline rclcpp/test/rclcpp/test_parameter_event_handler.cpp]: The original purpose of the test was to check the impact of content filter for add_parameter_callback().  
Therefore, it is recommended to use add_parameter_callback() for test.  
What do you think about making this change?  
```
  const std::string remote_node1_param_name = "param_node1";
  const std::string remote_node2_param_name = "param_node2";
  remote_node1->declare_parameter(remote_node1_param_name, 10);
  remote_node2->declare_parameter(remote_node2_param_name, "Default");
 
+   // Add an explanation similar to the one in above test.
+  param_handler.reset(); 
+  param_handler = std::make_shared<TestParameterEventHandler>(node);
+ 
```

Comment (fujitatomoya) [reply rclcpp/test/rclcpp/test_parameter_event_handler.cpp]: yeah that is actually true, we should call `add_parameter_callback()` in this test. i will borrow your suggestion to make the test pass with some extra comments.

**Comment by fujitatomoya** [comment]
i am not sure what the CI warning telling me here.

```console
rclcpp.cpplint.readability/braces [5] (/home/jenkins-agent/workspace/ci_linux/ws/src/ros2/rclcpp/rclcpp/test/rclcpp/test_parameter_event_handler.cpp:501)
If an else has a brace on one side, it should have it on both
```

**Comment by fujitatomoya** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/27858/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20870/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/7723/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26838/)

**Comment by fujitatomoya** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/27859/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20871/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/7724/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26839/)

**Review by Barry-Xu-2018 — APPROVED** [review]
