### PR TITLE
Make ring buffer thread-safe

### LINKED ISSUE #1007: Race condition in MultiThreadedExecutor with intra_process communication resulting in dequeuing ring buffer before enqueuing
There is a race condition in the `MultiThreadedExecutor` that happens during the `test_multithreahed.multi_consumer_intra_process` test in `test_rclcpp`. The `intra_process_buffer`'s `ring_buffer_implementation` has dequeue() called without any data. It may be that some process is calling dequeue() right after another has checked has_data().

This bug results in a flakey test with test_rclcpp, but it's fairly reliable to reproduce with sufficient repeat-until-fail iterations. 

https://ci.ros2.org/view/nightly/job/nightly_linux_repeated/1780/testReport/(root)/projectroot/gtest_multithreaded__rmw_fastrtps_cpp/
https://ci.ros2.org/job/ci_windows/9412/testReport/

### PR DESCRIPTION
**Pull request by audrow**
Fixes #1007, but there is a logical race condition that results in the same error, see #1212.

### CODE REVIEW

File: rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp [hunk 1]
```diff
@@ -112,7 +115,7 @@ class RingBufferImplementation : public BufferImplementationBase<BufferT>
   size_t read_index_;
   size_t size_;
 
-  std::mutex mutex_;
+  mutable std::recursive_mutex recursive_mutex_;
```
Comment (fujitatomoya) [inline rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp:118]: this has to be std::recursive_mutex instead mutex? as far as i checked, recursive_mutex takes time more than mutex. And i do not see the necessity so far, could you elaborate the case?

File: rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp [hunk 2]
```diff
@@ -88,16 +88,19 @@ class RingBufferImplementation : public BufferImplementationBase<BufferT>
 
   inline size_t next(size_t val)
   {
+    std::lock_guard<std::recursive_mutex> lock(recursive_mutex_);
```
Comment (fujitatomoya) [inline rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp:91]: I think that methods for `next`, `has_data` and `is_full` can be implemented via reader lock, using std::shared_mutex instead of std::mutex.

Comment (audrow) [reply rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp:91]: I think you're right.  I'll give this a try.

File: rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp (hunk 1 above)
Comment (audrow) [reply rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp:118]: I use the recursive mutex because `enqueue()` and `dequeue()` call `next()`, `has_data()`, and `is_full()`, which have locks in them.

File: rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp (hunk 2 above)
Comment (audrow) [reply rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp:91]: I tried using a `shared_mutex` with a `unique_lock` (also tried `lock_guard`) in the write functions (i.e., `enqueue()` and `dequeue()`) and `shared_lock`s in the read functions (i.e., `next()`, `has_data()`, and `is_full()`).  This doesn't work because these read operations are called in the write functions, causing a deadlock.

Any ideas on how to use a `shared_mutex` on the read functions, considering that the read functions are called in the write functions?

Comment (fujitatomoya) [reply rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp:91]: basically I think that mutex should be aligned with data but function.

how about the following?

- `enqueue` w/o `next` / `is_full` and use `unique_lock`
- `dequeue` w/o `has_data` / `next` and use `unique_lock`
- `next` with `shared_lock`
- `has_data` with `shared_lock`
- `is_full` with `shared_lock` 

with above,

- it can keep the interfaces compatible.
- it can use reader/writer lock instead of mutex. (also no need for recursive mutex)

I think that we should avoid the complicated code with mutex, but since this is the place for performance, I'd think using shared_mutex would be better.

File: rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp [hunk 3]
```diff
@@ -112,7 +131,7 @@ class RingBufferImplementation : public BufferImplementationBase<BufferT>
   size_t read_index_;
   size_t size_;
 
-  std::mutex mutex_;
+  mutable std::shared_timed_mutex mutex_;
```
Comment (fujitatomoya) [inline rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp:134]: are we going to use timeout for lock in the future? could you explain why you pick the `shared_timed_mutex` instead of `shared_mutex`?

Comment (audrow) [reply rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp:134]: Good question.  `rclcpp` defaults to using C++14, and in C++14 `shared_mutex` was renamed to `shared_timed_mutex` since it had timing in it.  `shared_mutex` is available from C++17 onwards. (See [here](https://stackoverflow.com/a/40207246/3335057) or [here](https://stackoverflow.com/a/42302130/3335057).)

**Comment by audrow** [comment]
@fujitatomoya I went back to using regular `mutex`s because it was brought up to me that the functions we are reading from are likely quicker than the logic associated with checking for the `shared_timed_mutex`'s lock.

File: rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp [hunk 4]
```diff
@@ -55,55 +59,125 @@ class RingBufferImplementation : public BufferImplementationBase<BufferT>
...
   inline size_t next(size_t val)
   {
-    return (val + 1) % capacity_;
+    std::lock_guard<std::mutex> lock(mutex_);
+    return next_(val);
   }
 
+  /// Get if the ring buffer has at least one element stored
+  /**
+   * This member function is not thread-safe.
```
Comment (jacobperron) [inline rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp:120]: Looks like this function *is* thread-safe.

Comment (audrow) [reply rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp:120]: Good catch!

**Comment by audrow** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11438/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6652/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9380/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11340/)

**Comment by fujitatomoya** [comment]
@audrow 

> likely quicker than the logic associated with checking for the shared_timed_mutex's lock.

interesting, thanks for the information and notification!
