### PR TITLE
Deprecate the shared_ptr<MessageT> subscription callback signatures

### LINKED ISSUE #2972: Deprecated subscription callback signatures are still compiling
### Generated by Generative AI

No

### Operating System:

Linux mini1235-XPS-15-9520 6.8.0-86-generic #87-Ubuntu SMP PREEMPT_DYNAMIC Mon Sep 22 18:03:36 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

### ROS version or commit hash:

Rolling

### RMW implementation (if applicable):

_No response_

### RMW Configuration (if applicable):

_No response_

### Client library (if applicable):

_No response_

### 'ros2 doctor --report' output

<details><summary>ros2 doctor --report</summary>

```console
<COPY OUTPUT HERE>
```
</details>

### Steps to reproduce issue

1. Create subscription with deprecated syntax
```
sub_ = this->create_subscription<std_msgs::msg::Int32>(
      input,
      10,
      [](std::shared_ptr<std_msgs::msg::Int32> msg)
```

### Expected behavior

Reports error or warning when compile

### Actual behavior

Nothing happen

### Additional information

https://docs.ros.org/en/rolling/Releases/Release-Jazzy-Jalisco.html#deprecated-subscription-callback-signatures-were-removed

states that

> Back in Humble, subscription signatures of the form ``void callback(std::shared_ptr<MessageT>)`` and ``void callback(std::shared_ptr<MessageT>, const rclcpp::MessageInfo &)`` were deprecated.

> In Jazzy, these subscription signatures have been removed.
Users should switch to using ``void callback(std::shared_ptr<const MessageT>)`` or ``void callback(std::shared_ptr<const MessageT>, const rclcpp MessageInfo &)``.

Related PRs in this repo are:
- https://github.com/ros2/rclcpp/pull/1598
- https://github.com/ros2/rclcpp/pull/1713 - deprecates the syntax
- https://github.com/ros2/rclcpp/pull/2431 - removes the deprecation warnings

In the latest version, I am still able to use the syntax `std::shared_ptr<MessageT>` in the callback, is this intended?
If no, why don't we remove the deprecated signature as well?https://github.com/ros2/rclcpp/blob/4d14414d9108f11e0a3fad826c0f43a383dbaf41/rclcpp/include/rclcpp/any_subscription_callback.hpp#L140-L154

This is something I noticed in https://github.com/ros2/ros2_documentation/issues/2333#issuecomment-3468836714, where the https://github.com/ros2/demos/pull/532/ changes from  `const sensor_msgs::msg::Image::SharedPtr` to `sensor_msgs::msg::Image::ConstSharedPtr` and breaks the tutorial

### PR DESCRIPTION
**Pull request by mini-1235**
## Description

- Add static assert for removed subscription callback signatures

Fixes #2972

### Is this user-facing behavior change?

Yes

### Did you use Generative AI?

No

### Additional Information

When working on this PR, I noticed that #1713 only deprecates `MessageT`. However, looking at the comment here:
https://github.com/ros2/rclcpp/blob/eb49444c3229f03255083d7992564b83ec2d9e2c/rclcpp/include/rclcpp/any_subscription_callback.hpp#L140-L154
it looks like the type_adaptation/serialized message are not yet deprecated, how should we proceed?

In the meantime, I have also updated the tests for type_adaptation/serialized  to use `std::shared_ptr<const>`

### CODE REVIEW

**Comment by mini-1235** [comment]
I have pulled and built the ROS2 repos from https://raw.githubusercontent.com/ros2/ros2/rolling/ros2.repos  (Please let me know if there are any other repos I should include)

Removing `std::shared_ptr<MessageT>` would have an impact on:
- robot_state_publisher: https://github.com/ros/robot_state_publisher/pull/241
- real_time_support: https://github.com/ros2/realtime_support/pull/135 (example)
- message filter: https://github.com/ros2/message_filters/pull/222 (test only)
- demos: https://github.com/ros2/demos/pull/754

Removing/Deprecating `std::shared_ptr<TypeAdapter/Serialize Message>` would affect:
- demos: https://github.com/ros2/demos/pull/754
- ros2 tracing: https://github.com/ros2/ros2_tracing/pull/217 (test only)
- rosbag2 (examples and test): https://github.com/ros2/rosbag2/pull/2225
- system test: https://github.com/ros2/system_tests/pull/575

File: rclcpp/include/rclcpp/any_subscription_callback.hpp [hunk 1]
```diff
@@ -392,6 +392,34 @@ class AnySubscriptionCallback
...
+      typename scbth::callback_type,
+      std::function<void(std::shared_ptr<rclcpp::SerializedMessage>)>
+      >::value ||
+      rclcpp::function_traits::same_arguments<
+      typename scbth::callback_type,
+      std::function<void(std::shared_ptr<rclcpp::SerializedMessage>, const rclcpp::MessageInfo &)>
+      >::value;
+    static_assert(!is_invalid_signature,
+      "std::shared_ptr<> callback signature is unsupported "
+      "Use std::shared_ptr<const> or std::unique_ptr<> instead.");
```
Comment (fujitatomoya) [inline rclcpp/include/rclcpp/any_subscription_callback.hpp]: It is true that those signatures have been deprecated for a long time `as comment states`, but my concern is that can we really enforce this all the sudden? i understand this is right thing to do, but this can possibly break the user space without any notification. 

IMO, [Deprecation Period](https://docs.ros.org/en/rolling/The-ROS2-Project/Contributing/Developer-Guide.html#deprecation-strategy) should still be given for user space for next release, and then we can enforce the invalid signature assertion?

@mini-1235 @mjcarroll @ahcorde what do you think?

**Review by fujitatomoya — COMMENTED** [review]
@mini-1235 thanks for fixing up all the related packages and repositories.

changing signatures are totally fine things to do including this PR, but i want to discuss with you on either we should enforcement or deprecation here for the next release.

File: rclcpp/include/rclcpp/any_subscription_callback.hpp (hunk 1 above)
Comment (mini-1235) [reply rclcpp/include/rclcpp/any_subscription_callback.hpp]: I think there are two points to discuss here:

1. `std::shared_ptr<MessageT>`: this was deprecated back in August 2021, but the deprecation warning was accidentally removed in February 2024. It looks like the majority of the ROS 2 core repositories are fine, but I am not entirely sure about other packages. For example, Nav2 still uses `std::shared_ptr<MessageT>` a lot: https://github.com/mini-1235/navigation2/commit/9a6aca5434fc6878734e735b6ee3583aec2f4158

2. `std::shared_ptr<TypeAdapter/Serialize Message>`: this signature was actually never deprecated, so I think it should be deprecated instead of removed

In my current PR, I removed all forms of `std::shared_ptr<>` mainly for testing purposes. I am open to any suggestions on how this should be handled :)

Comment (wjwwood) [reply rclcpp/include/rclcpp/any_subscription_callback.hpp]: Do you have a link to the commit that removed the deprecation?

We could re-deprecate it, just to be safe, and add the static asserts after a cycle.

I'm actually curious what the `shared_ptr<T>` does right now. I guess it must be taking a copy (e.g. as a `unique_ptr<T>`) and making a new `shared_ptr<T>` for each callback?

Comment (mini-1235) [reply rclcpp/include/rclcpp/any_subscription_callback.hpp]: > Do you have a link to the commit that removed the deprecation?

https://github.com/ros2/rclcpp/pull/2431

> We could re-deprecate it, just to be safe, and add the static asserts after a cycle.

OK!

> I'm actually curious what the shared_ptr<T> does right now. I guess it must be taking a copy (e.g. as a unique_ptr<T>) and making a new shared_ptr<T> for each callback?

I haven't had time to look into the implementation deeply yet, so I can only speak based on the experiments I have run so far. With intra-process communication enabled, I am seeing that for n subscribers, there are n-1 copies made

**Comment by mini-1235** [comment]
I am not sure how to deal with the deprecated tests here
https://github.com/ros2/rclcpp/blob/1500449c112fc899d62207f43c6e63db10654b57/rclcpp/test/rclcpp/test_any_subscription_callback.cpp#L683-L723

Should I add `#define RCLCPP_AVOID_DEPRECATIONS_FOR_UNIT_TESTS 1` like the previous PR or any other better approach?

**Comment by mjcarroll** [comment]
> Should I add #define RCLCPP_AVOID_DEPRECATIONS_FOR_UNIT_TESTS 1 like the previous PR or any other better approach?

Please do!

Then we can remove them in the next cycle with find/replace

**Comment by mini-1235** [comment]
> > Should I add #define RCLCPP_AVOID_DEPRECATIONS_FOR_UNIT_TESTS 1 like the previous PR or any other better approach?
> 
> Please do!
> 
> Then we can remove them in the next cycle with find/replace

Added!

**Review by fujitatomoya — APPROVED** [review]
lgtm with green CI.

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclcpp#2975
Gist: https://gist.githubusercontent.com/fujitatomoya/76e9ee5ac26e9d10c870d5850669c3aa/raw/6757efc08e3846630a7c8cd8a07f4905bcd864c1/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp
TEST args:  --packages-above rclcpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/17705
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/26445/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20073/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/6206/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26155/)

**Comment by mjcarroll** [comment]
@mini-1235 looks like there were some uncrustify issues here.  Can you address those?

**Comment by mini-1235** [comment]
As reported in https://github.com/uncrustify/uncrustify/issues/4250, this is a known issue in uncrustify 0.78.1. To avoid timeout, I will skip the uncrustify check here

**Comment by fujitatomoya** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/26701/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/20328/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/6500/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/26287/)

**Review by ahcorde — APPROVED** [review]
