### PR TITLE
apply actual QoS from rmw to the IPC publisher.

### LINKED ISSUE #2705: SystemDefaultsQoS - force to have depth > 0 for Publishers
#### Feature description

For SystemDefaultsQoS to work out of the box for IPC, it needs to always strictly have a depth setting > 0. When used in a subscription out of the box, this works fine. For example:

```
  footprint_sub_ = create_subscription<geometry_msgs::msg::Polygon>(
    "footprint",
    nav2_util::DefaultQoS(),
    std::bind(&Costmap2DROS::setRobotFootprintPolygon, this, std::placeholders::_1));
```

However, when used in a publisher, it fails. For example:

```
  footprint_pub_ = create_publisher<geometry_msgs::msg::PolygonStamped>(
    "published_footprint", rclcpp::SystemDefaultsQoS());
```

or 

```
  state_pub_ = this->create_publisher<nav2_msgs::msg::CollisionDetectorState>(
    "collision_detector_state", rclcpp::SystemDefaultsQoS());
```

with the error

> [component_container_isolated-7] [ERROR] [1734048098.404790594] [local_costmap.local_costmap]: Original error: intraprocess communication is not allowed with a zero qos history depth value

---

Thus, I feel that we should update the default for SystemDefaultsQoS for publishers (or in general) to be `1` if not already `> 1` so that folks migrating or implementing IPC don't run into a cacophony of issues, one for each publisher. I understand this comes from the RMW/DDS, but it seems to me this needs to be updated since `SystemDefaultsQoS` is a key "default" QoS profile. Having that simply not work for a core ROS 2 feature seems intrinsically problematic :-)  It was a bit subtle for me to identify this, so fixing this for everyone else in the future would be ideal.

For now, I'm creating a new `nav2_util::DefaultPublisherQoS()` to resolve this on my end, but I believe it should be fixed in `rclcpp` / below for the general user case

### PR DESCRIPTION
**Pull request by fujitatomoya**
closes https://github.com/ros2/rclcpp/issues/2705

note: backport required to jazzy and humble.

### CODE REVIEW

File: rclcpp/include/rclcpp/publisher.hpp [hunk 1]
```diff
@@ -148,29 +148,32 @@ class Publisher : public PublisherBase
...
       auto ipm = context->get_sub_context<rclcpp::experimental::IntraProcessManager>();
-      // Register the publisher with the intra process manager.
-      if (qos.history() != rclcpp::HistoryPolicy::KeepLast) {
+      // Check if the QoS is compatible with intra-process.
+      auto qos_profile = get_actual_qos();
+      if (qos_profile.history() != rclcpp::HistoryPolicy::KeepLast) {
         throw std::invalid_argument(
                 "intraprocess communication allowed only with keep last history qos policy");
       }
-      if (qos.depth() == 0) {
```
Comment (fujitatomoya) [inline rclcpp/include/rclcpp/publisher.hpp:163]: this was the direct cause of https://github.com/ros2/rclcpp/issues/2705, QoS via the argument is NOT the actual QoS from rmw implementation with SystemDefaultQoS(this means rmw implementation default). So here it just uses `RMW_QOS_POLICY_DEPTH_SYSTEM_DEFAULT`, which is 0, and eventually causes this exception.

by the way, subscription does not have this problem since it already calls `get_actual_qos()` for IPC subscriber. this is why we do not have the problem on creation of IPC subscription.

File: rclcpp/test/rclcpp/test_publisher.cpp [hunk 2]
```diff
@@ -187,6 +187,21 @@ TEST_F(TestPublisher, various_creation_signatures) {
   }
 }
 
+/*
+   Testing publisher with intraprocess enabled and SystemDefaultQoS
+ */
+TEST_F(TestPublisher, test_publisher_with_system_default_qos) {
```
Comment (fujitatomoya) [inline rclcpp/test/rclcpp/test_publisher.cpp:193]: this test simulate the https://github.com/ros2/rclcpp/issues/2705

**Comment by fujitatomoya** [comment]
@alsora i would like to request the review.

**Review by mjcarroll — APPROVED** [review]

File: rclcpp/include/rclcpp/publisher.hpp [hunk 3]
```diff
@@ -148,29 +148,32 @@ class Publisher : public PublisherBase
   {
     // Topic is unused for now.
     (void)topic;
+    (void)qos;
     (void)options;
```
Comment (clalancette) [inline rclcpp/include/rclcpp/publisher.hpp]: Sigh.  I'm wondering whether we should deprecate this API signature, and just reduce this to:

```
virtual
void
post_init_setup(rclcpp::node_interfaces::NodeBaseInterface * node_base);
```

As far as I can tell, there are no downstream users of this API, and just continually setting this to (void) seems useless to me.  Thoughts?

**Review by clalancette — COMMENTED** [review]
This is absolutely the right change, thanks for finding it @fujitatomoya .  I left one thought inline.

File: rclcpp/include/rclcpp/publisher.hpp (hunk 3 above)
Comment (fujitatomoya) [reply rclcpp/include/rclcpp/publisher.hpp]: i am okay with that.

maybe we can refactor the following, but i would like to do that with another PR.

- introduce `intra_process_init` non-virtual function under `Publisher` and `Subscriber` classes, and implement whatever needs to be setup for intra-process pub/sub.
- deprecate `post_init_setup` for `Publisher` and `Subscriber` classes, `Subscriber` one is empty already. Or we can keep it for fully virtual function? so that user can override this to setup post process initialization?

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclcpp#2707
Gist: https://gist.githubusercontent.com/fujitatomoya/1864914d39a602bf8236970ff6d5d595/raw/1e4e0757031d664d082ecea21c6e706f36eee0b0/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp
TEST args:  --packages-above rclcpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14955
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22268/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16529/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1792/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23055/)

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclcpp#2707
Gist: https://gist.githubusercontent.com/fujitatomoya/77dd98edbbde2b1cf7e7afdf880e66d3/raw/1e4e0757031d664d082ecea21c6e706f36eee0b0/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp
TEST args:  --packages-above rclcpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14961
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22274/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16535/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1800/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23062/)

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclcpp#2707
Gist: https://gist.githubusercontent.com/fujitatomoya/0f28f78e9f92d6bde8551ba4f679d785/raw/1e4e0757031d664d082ecea21c6e706f36eee0b0/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp
TEST args:  --packages-above rclcpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14964
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22279/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16538/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1803/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23065/)

**Comment by fujitatomoya** [comment]
@Mergifyio backport humble jazzy
