### PR TITLE
try aborting before canceling 1st on dtor of ServerGoalHandle.

### LINKED ISSUE #2948: ServerGoalHandle may throw from a destructor
### Generated by Generative AI

_No response_

### Operating System:

ubuntu 22

### ROS version or commit hash:

humble

### RMW implementation (if applicable):

_No response_

### RMW Configuration (if applicable):

_No response_

### Client library (if applicable):

rclcpp_action

### Steps to reproduce issue

Destructor of ServerGoalHandle may throw an exception from `on_terminate_state` callback https://github.com/ros2/rclcpp/blob/rolling/rclcpp_action/include/rclcpp_action/server_goal_handle.hpp#L250, callback is defined here https://github.com/ros2/rclcpp/blob/rolling/rclcpp_action/include/rclcpp_action/server.hpp#L511. Since destructors are `nothrow` in C++11 this results in termination of a program.

### Expected behavior

destructors should not throw

### Actual behavior

.

### Additional information

PS: the goal should be aborted on destruction rather than canceled to match design spec
```
ABORTED - The goal was terminated by the action server without an external request.
CANCELED - The goal was canceled after an external request from an action client.
```
https://design.ros2.org/articles/actions.html

### PR DESCRIPTION
**Pull request by fujitatomoya**
## Description

Depends on https://github.com/ros2/rcl/pull/1257

Fixes https://github.com/ros2/rclcpp/issues/2948 and https://github.com/ros2/rclcpp/issues/2757

### Is this user-facing behavior change?

Yes.

before, on the destruction of `ServerGoalHandle`, it only tries to cancel the goal.
after, it tries to abort the goal 1st, and if not possible in the current state, it then falls back to cancel the goal.

the goal should be aborted if possible in the 1st place on destruction rather than canceled to match design spec as following.

- ABORTED: The goal was terminated by the action server without an external request.
- CANCELED: The goal was canceled after an external request from an action client.

https://design.ros2.org/articles/actions.html

### Did you use Generative AI?

No

### CODE REVIEW

File: rclcpp_action/src/server_goal_handle.cpp [hunk 1]
```diff
@@ -137,4 +137,22 @@ ServerGoalHandleBase::try_canceling() noexcept
...
+  const bool is_abortable = rcl_action_goal_handle_is_abortable(rcl_handle_.get());
+  if (is_abortable) {
+    // Transition to ABORTED
+    ret = rcl_action_update_goal_state(rcl_handle_.get(), GOAL_EVENT_ABORT);
+    if (RCL_RET_OK != ret) {
+      return false;
+    }
+  }
+
+  return true;
```
[the remark this answers is not in the document]
Comment (fujitatomoya) [reply rclcpp_action/src/server_goal_handle.cpp]: This is actually true. The same fix should be applied to `ServerGoalHandleBase::try_canceling()`.

**Comment by fujitatomoya** [comment]
@sloretz @ahcorde @Barry-Xu-2018 can either of you take a look at this?

**Comment by fujitatomoya** [comment]
Pulls: ros2/rcl#1257, ros2/rclcpp#2953
Gist: https://gist.githubusercontent.com/fujitatomoya/139c87a7db7c064754bb468fff43a36b/raw/b9b000f0c877922d50ccf5d8cbf6b9acf832c901/ros2.repos
BUILD args:  --packages-above-and-dependencies rcl_action rclcpp_action
TEST args:  --packages-above rcl_action rclcpp_action
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16943
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24862/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18895/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/4319/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/25373/)

File: rclcpp_action/src/server_goal_handle.cpp [hunk 2]
```diff
@@ -135,6 +135,24 @@ ServerGoalHandleBase::try_canceling() noexcept
...
   }
 
-  return false;
+  return is_cancelable;
+}
+
+bool
+ServerGoalHandleBase::try_aborting() noexcept
+{
+  std::lock_guard<std::mutex> lock(rcl_handle_mutex_);
```
Comment (ahcorde) [inline rclcpp_action/src/server_goal_handle.cpp:145]: include `<mutex>`

**Review by ahcorde — CHANGES_REQUESTED** [review]

File: rclcpp_action/include/rclcpp_action/server_goal_handle.hpp [hunk 3]
```diff
@@ -108,6 +110,12 @@ class ServerGoalHandleBase
   bool
   try_canceling() noexcept;
 
+  /// Transition the goal to aborted state if it never reached a terminal state.
```
Comment (jmachowinski) [inline rclcpp_action/include/rclcpp_action/server_goal_handle.hpp:114]:
```suggestion
  /// Transition the goal to aborted state if it never reached a terminal state.
  /// Returns true if transitioned to aborted, else false.
```

File: rclcpp_action/src/server_goal_handle.cpp (hunk 2 above)
Comment (fujitatomoya) [reply rclcpp_action/src/server_goal_handle.cpp:145]: fixed in https://github.com/ros2/rclcpp/pull/2953/commits/b1d935edb9d102ac913a278b840dabd87746c5b6

File: rclcpp_action/include/rclcpp_action/server_goal_handle.hpp (hunk 3 above)
Comment (fujitatomoya) [reply rclcpp_action/include/rclcpp_action/server_goal_handle.hpp:114]: fixed in https://github.com/ros2/rclcpp/pull/2953/commits/b1d935edb9d102ac913a278b840dabd87746c5b6

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclcpp#2953, ros2/rcl#1257
Gist: https://gist.githubusercontent.com/fujitatomoya/29eaa6283bf89601bd57b2b78c56ebde/raw/b9b000f0c877922d50ccf5d8cbf6b9acf832c901/ros2.repos
BUILD args:  --packages-up-to rcl_action rclcpp_action
TEST args:  --packages-select rcl_action rclcpp_action
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16963
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24882/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18916/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/4344/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/25394/)
