### PR TITLE
subordinate node consistent behavior and update docstring.

### LINKED ISSUE #2795: rclcpp::Node::get_parameter overloads undocumented inconsistent behavior
### Operating System:

Ubuntu 24.04

### ROS version or commit hash:

jazzy (from apt)

### RMW implementation (if applicable):

_No response_

### RMW Configuration (if applicable):

_No response_

### Client library (if applicable):

rclcpp

### 'ros2 doctor --report' output

<details><summary>ros2 doc --report</summary>

```console
/opt/ros/jazzy/lib/python3.12/site-packages/ros2doctor/api/__init__.py: 162: UserWarning: Fail to call PackageReport class functions.

   NETWORK CONFIGURATION
inet         : 127.0.0.1
inet4        : ['127.0.0.1']
inet6        : ['::1']
netmask      : 255.0.0.0
device       : lo
flags        : 73<RUNNING,LOOPBACK,UP>
mtu          : 65536
inet         : 192.168.1.109
inet4        : ['192.168.1.109']
ether        : d8:43:ae:0f:cd:73
inet6        : ['fe80::da43:aeff:fe0f:cd73%enp8s0']
netmask      : 255.255.255.0
device       : enp8s0
flags        : 4163<RUNNING,BROADCAST,MULTICAST,UP>
mtu          : 1500
broadcast    : 192.168.1.255
inet         : 192.168.1.143
inet4        : ['192.168.1.143']
ether        : 14:ac:60:26:e7:37
inet6        : ['fe80::cd82:9627:3deb:edf0%wlp15s0']
netmask      : 255.255.255.0
device       : wlp15s0
flags        : 4163<RUNNING,BROADCAST,MULTICAST,UP>
mtu          : 1500
broadcast    : 192.168.1.255

   PLATFORM INFORMATION
system           : Linux
platform info    : Linux-6.11.0-19-generic-x86_64-with-glibc2.39
release          : 6.11.0-19-generic
processor        : x86_64

   QOS COMPATIBILITY LIST
compatibility status    : No publisher/subscriber pairs found

   RMW MIDDLEWARE
middleware name    : rmw_fastrtps_cpp

   ROS 2 INFORMATION
distribution name      : jazzy
distribution type      : ros2
distribution status    : active
release platforms      : {'debian': ['bookworm'], 'rhel': ['9'], 'ubuntu': ['noble']}

   TOPIC LIST
topic               : none
publisher count     : 0
subscriber count    : 0
```
</details>

### Steps to reproduce issue

Create a subnode with a subnamespace, use it declare and set a parameter, and then try to get the parameter using the different overloads of the `get_parameter()` method.
Example:
```cpp
  auto subnode = node->create_sub_node("subnode");
  subnode->declare_parameter("param_name", 5);

  std::cout << subnode->get_parameter("param_name").get_value<int>() << std::endl;

  rclcpp::Parameter param;
  subnode->get_parameter("param_name", param);
  std::cout << param.get_value<int>() << std::endl;

  int param_int;
  subnode->get_parameter("param_name", param_int);
  std::cout << param_int << std::endl;

  std::cout << subnode->get_parameter_or("param_name", 666) << std::endl;

  subnode->get_parameter_or("param_name", param_int, 666);
  std::cout << param_int << std::endl;
```
Expected output:
```
5
5
5
5
5
```
Actual output:
```
5
5
1
666
666
```
:'(

### Expected behavior

All the overrides of the method `get_parameter()` and `get_parameter_or()` should behave consistently, and not sometimes try to prepend the subnode namespace and sometimes not.

### Actual behavior

The override
```cpp
template <typename ParameterT>
bool rclcpp::Node::get_parameter (const std::string& name, ParameterT& parameter) const
```
and both variants of `get_parameter_or()` call the `extend_name_with_sub_namespace()` function that modifies the name of the parameter. The rest of the methods (including `set_parameter()` and `declare_parameter()`) do not. This behavior is not documented, it is inconsistent, and it cost me a lot of debugging time.

### Additional information

I think the root of the problem is that the implementation of subnodes is only half finished, leading to bugs and unexpected behavior like this. It's as if somebody simply committed and pushed his WIP code when in the middle of implementing subnodes. Subnode parameters in ROS2 are almost never namespaced, which makes it hard to solve conflicting parameter names.

The short-term solution is to remove the call to `extend_name_with_sub_namespace()` (which btw. seems to be broken or at the least not behaving as in ROS1 w.r.t. the `/`, `.` and `~` special symbols).

I think the correct solution however would be to finish implementing subnodes also for parameters... and finish writing the documentation...

### PR DESCRIPTION
**Pull request by fujitatomoya**
closes #2795 

> [!NOTE]
> `extend_name_with_sub_namespace` is inline function, so user must rebuild the application with rclcpp to get this fix. besides that, this is behavior change could break the application. i am not inclined to backport this. thoughts?

### CODE REVIEW

File: rclcpp/include/rclcpp/node.hpp [hunk 1]
```diff
@@ -1559,6 +1559,10 @@ class Node : public std::enable_shared_from_this<Node>
    * which has been created using an existing instance of this class, but which
    * has an additional sub-namespace (short for subordinate namespace)
    * associated with it.
+   * A suboardinate node and an instance of this class share all the node interfaces
+   * such as `rclcpp::node_interfaces::NodeParameterInterface`.
+   * Suboardinate nodes are primarily used to organize namespaces and provide a
+   * hierarchical structure, but they are not meant to be completely independent nodes.
```
Comment (fujitatomoya) [inline rclcpp/include/rclcpp/node.hpp]: i think that we explicitly add this description to avoid confusion about sub-node behavior.

File: rclcpp/src/rclcpp/node.cpp [hunk 2]
```diff
@@ -689,7 +689,7 @@ Node::create_generic_client(
     node_base_,
     node_graph_,
     node_services_,
-    service_name,
+    extend_name_with_sub_namespace(service_name, this->get_sub_namespace()),
```
Comment (fujitatomoya) [inline rclcpp/src/rclcpp/node.cpp:692]: This is a bug has been there for a long time. Only this creating generic client misses to call this API to extend the name with sub-node.

**Comment by fujitatomoya** [comment]
@jmachowinski @mjcarroll can you review this?

**Review by wjwwood — APPROVED** [review]

File: rclcpp/include/rclcpp/node.hpp (hunk 1 above)
Comment (christophebedard) [inline rclcpp/include/rclcpp/node.hpp]:
```suggestion
   * A subordinate node and an instance of this class share all the node interfaces
   * such as `rclcpp::node_interfaces::NodeParameterInterface`.
   * Subordinate nodes are primarily used to organize namespaces and provide a
   * hierarchical structure, but they are not meant to be completely independent nodes.
```

Comment (fujitatomoya) [reply rclcpp/include/rclcpp/node.hpp]: @christophebedard thanks for fixing this!

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclcpp#2822
Gist: https://gist.githubusercontent.com/fujitatomoya/4eae4734591a7b22690e7f7ed0abbcde/raw/defed4a27eb0e0fbfaab46dd7fc7a787ef29f8b6/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp
TEST args:  --packages-above rclcpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15726
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/23193/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/17407/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/2659/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/24067/)

**Review by christophebedard — APPROVED** [review]

**Comment by christophebedard** [comment]
We can probably get this into Rolling during the freeze, before Kilted branches off (which it hasn't yet IIUC).

**Comment by fujitatomoya** [comment]
@christophebedard what do you think about backport ? https://github.com/ros2/rclcpp/pull/2822#issue-3009358559

**Comment by christophebedard** [comment]
Yeah, I agree, maybe we should hold off on backporting, at least for now. This is the kind of issue that users probably worked around. If someone requests a backport, then we can consider it more seriously.

**Comment by fujitatomoya** [comment]
> [!WARNING]
> DO NOT MERGE THIS, WE ARE NOW BRANCHING KILTED.

**Comment by fujitatomoya** [comment]
@Mergifyio backport kilted

**Comment by DLu** [comment]
Is there a tutorial on how to use this yet? :-D

**Comment by christophebedard** [comment]
Not as far as I know, but I opened an issue for that here: https://github.com/ros2/ros2_documentation/issues/5457.

**Comment by v-lopez** [comment]
Is there a chance to have this backported to jazzy? Or a workaround for it?

**Comment by fujitatomoya** [comment]
@v-lopez unfortunately i do not think so, as the PR header says this breaks the user space. it looks like we did backport this to kilted, but it is different situation. for kilted, we were just working on the branching from rolling, so that is not counted as backport.
