### PR TITLE
remove I/O from signal handler.

### LINKED ISSUE #2982: Deadlock when handling signals (e.g. SIGTERM)
### Generated by Generative AI

_No response_

### Operating System:

Linux <hostname> 4.18.0-553.81.1.el8_10.x86_64 #1 SMP Thu Oct 16 14:01:33 EDT 2025 x86_64 x86_64 x86_64 GNU/Linux

### ROS version or commit hash:

HUMBLE 

### RMW implementation (if applicable):

rmw_fastrtps_cpp

### RMW Configuration (if applicable):

_No response_

### Client library (if applicable):

rclcpp

### Steps to reproduce issue

1. Write a trivial ROS application that enters a spin() loop and in another thread does some file I/O  
2. Launch rclcpp application 
3. Use "kill" command to issue a SIGTERM 
4. Repeat until application hangs on shutdown.  Depending on the amount of I/O, this bug may be hard to trigger requiring 100's or 1000's of attempts to trigger. 

### Expected behavior

Application should never deadlock on signal handler. 

### Actual behavior

Application deadlocks with the following stack trace. 

```
> #0  0x00007fe61b7e215c in __lll_lock_wait_private () from /lib64/libc.so.6
> #1  0x00007fe61b90ab68 in __fprintf_chk () from /lib64/libc.so.6
> #2  0x00007fe61ce19adf in rcutils_logging_console_output_handler () from /opt/ros/humble/lib/librcutils.so
> #3  0x00007fe6231da396 in rcl_logging_multiple_output_handler () from /opt/ros/humble/lib/librcl.so
> #4  0x00007fe623b6ac26 in rclcpp_logging_output_handler () from /opt/ros/humble/lib/librclcpp.so
> #5  0x00007fe61ce19291 in rcutils_log () from /opt/ros/humble/lib/librcutils.so
> #6  0x00007fe623c22a15 in rclcpp::SignalHandler::signal_handler(int, siginfo_t*, void*) () from /opt/ros/humble/lib/librclcpp.so
> #7  <signal handler called>
> #8  0x00007fe61b844b7d in fwrite () from /lib64/libc.so.6
> #9  0x00007fe61c24a896 in std::ostream::write(char const*, long) () from /lib64/libstdc++.so.6
```

### Additional information

The issue is that that the signal handler attempts to write a log message.   Signal  handlers should never do I/O.

### PR DESCRIPTION
**Pull request by fujitatomoya**
## Description

Fixes https://github.com/ros2/rclcpp/issues/2982

### Is this user-facing behavior change?

Yes this fixes the possible deadlock via IO.

### Did you use Generative AI?

No.

### Additional Information

> [!NOTE]
> backport required for all downstream distros.

### CODE REVIEW

File: rclcpp/src/rclcpp/signal_handler.cpp [hunk 1]
```diff
@@ -260,6 +256,8 @@ SignalHandler::deferred_signal_handler()
 {
   while (true) {
     if (signal_received_.exchange(false)) {
+      int signum = signal_number_.load();
+      RCLCPP_INFO(get_logger(), "signal_handler(signum=%d)", signum);
```
Comment (fujitatomoya) [inline rclcpp/src/rclcpp/signal_handler.cpp:260]: This is the key point for this fix.
Having logging message in deferred signal handler which is normal thread, and prints the signal number which is installed via signal hander.

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclcpp#2986
Gist: https://gist.githubusercontent.com/fujitatomoya/dc183cb45013b37e59e2f7784377177f/raw/4d26e86d31206a149f509e73b3f95f44fb29e65d/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp
TEST args:  --packages-above rclcpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/17501
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/25911/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/19781/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/5502/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/25947/)

**Review by ahcorde — CHANGES_REQUESTED** [review]
Some signal handler. are failing

**Review by nugins99 — APPROVED** [review]
Changes look good.  Thanks!

**Comment by fujitatomoya** [comment]
@ahcorde yeah, i will take a look! thanks

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclcpp#2986, ros2/system_tests#576
Gist: https://gist.githubusercontent.com/fujitatomoya/2d25aacc1059cd394750fb9b88193f12/raw/9245a073dfdba8e93a15e000ecb0a0485a265fb1/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp test_rclcpp
TEST args:  --packages-above rclcpp test_rclcpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/17517
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/26010/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/19824/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/5576/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/25963/)

**Review by ahcorde — APPROVED** [review]

**Comment by jmachowinski** [comment]
Hm, this patch gets the job done, but It looks like using a std::future would make a cleaner implementation.

**Comment by fujitatomoya** [comment]
@jmachowinski yeah cannot disagree, i will try that with another PR when i have time or maybe `help-wanted` since it seems pretty straight-forward change.

**Comment by fujitatomoya** [comment]
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/19842/) (I do not think previous CI is related to this PR, but just in case.)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/5600/)

**Comment by fujitatomoya** [comment]
@Mergifyio backport kilted jazzy humble
