### PR TITLE
Avoid parsing arguments twice

### LINKED ISSUE #1412: init_and_remove_ros_arguments parse arguments two times
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - source
- Version or commit hash:
  - 018cfaa2197b94ed1517cc2860758e1b8db02bdb
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

```
$ ros2 run demo_nodes_cpp listener --ros-args --log-level debug
```

#### Expected behavior
```
<...>
[DEBUG] [1603184568.251432332] [rcl]: Couldn't parse arg 0 (/home/sharedata/Linux/ROS2/docker_ros2_master/local_install/lib/demo_nodes_cpp/listener) as a remap rule in its deprecated form. Error: Expected lexeme type (19) not found, search ended at index 87, at /home/sharedata/Linux/ROS2/docker_ros2_master/src/ros2/rcl/rcl/src/rcl/lexer_lookahead.c:233
<...>
```

#### Actual behavior

```
<...>
[DEBUG] [1603184568.251432332] [rcl]: Couldn't parse arg 0 (/home/sharedata/Linux/ROS2/docker_ros2_master/local_install/lib/demo_nodes_cpp/listener) as a remap rule in its deprecated form. Error: Expected lexeme type (19) not found, search ended at index 87, at /home/sharedata/Linux/ROS2/docker_ros2_master/src/ros2/rcl/rcl/src/rcl/lexer_lookahead.c:233
<...>
[DEBUG] [1603184568.253581614] [rcl]: Couldn't parse arg 0 (/home/sharedata/Linux/ROS2/docker_ros2_master/local_install/lib/demo_nodes_cpp/listener) as a remap rule in its deprecated form. Error: Expected lexeme type (19) not found, search ended at index 87, at /home/sharedata/Linux/ROS2/docker_ros2_master/src/ros2/rcl/rcl/src/rcl/lexer_lookahead.c:233
```

#### Additional information

https://github.com/ros2/rclcpp/blob/018cfaa2197b94ed1517cc2860758e1b8db02bdb/rclcpp/src/rclcpp/utilities.cpp#L59-L67

Fix: At https://github.com/ros2/rclcpp/blob/018cfaa2197b94ed1517cc2860758e1b8db02bdb/rclcpp/src/rclcpp/utilities.cpp#L69-L70, we need to check if `get_global_default_context()->get_rcl_context()` exist, and then decide to call `rcl_parse_arguments` or not.

### PR DESCRIPTION
**Pull request by iuhilnehc-ynos**
Fixes #1412

Signed-off-by: Chen Lihui <Lihui.Chen@sony.com>

### CODE REVIEW

File: rclcpp/src/rclcpp/utilities.cpp [hunk 1]
```diff
@@ -115,6 +95,48 @@ remove_ros_arguments(int argc, char const * const argv[])
...
+init_and_remove_ros_arguments(
+  int argc,
+  char const * const argv[],
+  const InitOptions & init_options)
+{
+  init(argc, argv, init_options);
+
+  using rclcpp::contexts::get_global_default_context;
+  auto rcl_context = get_global_default_context()->get_rcl_context();
+  return _remove_ros_arguments(argv, &(rcl_context->global_arguments), rcl_get_default_allocator());
```
Comment (fujitatomoya) [inline rclcpp/src/rclcpp/utilities.cpp:111]: leave this comment to share my understanding. Since context is initialized, it should get `global_arguments` from the context, not to call `rcl_parse_arguments` twice.

**Review by fujitatomoya — APPROVED** [review]
this makes sense to me.

File: rclcpp/src/rclcpp/utilities.cpp [hunk 2]
```diff
@@ -56,53 +57,32 @@ uninstall_signal_handlers()
...
-    &parsed_args,
+    args,
     alloc,
     &nonros_argc,
     &nonros_argv);
 
   if (RCL_RET_OK != ret || nonros_argc < 0) {
     // Not using throw_from_rcl_error, because we may need to append deallocation failures.
-    exceptions::RCLErrorBase base_exc(ret, rcl_get_error_state());
+    exceptions::RCLError exc(ret, rcl_get_error_state(), "");
```
Comment (ivanpauno) [inline rclcpp/src/rclcpp/utilities.cpp:80]: why this change?

**Review by ivanpauno — APPROVED** [review]
LGTM!

File: rclcpp/src/rclcpp/utilities.cpp (hunk 2 above)
Comment (iuhilnehc-ynos) [reply rclcpp/src/rclcpp/utilities.cpp:80]: to keep `init_and_remove_ros_arguments` throw the same exception type as the previous original code

**Comment by ivanpauno** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12909/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7863/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10626/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12858/)

**Comment by ivanpauno** [comment]
@iuhilnehc-ynos rebasing with master should fix the warnings

**Comment by ivanpauno** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12935/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7884/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10651/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12884/)
