### PR TITLE
Fix `start_type_description_service` param handling

### LINKED ISSUE #2892: Setting `start_type_description_service` param can fail when `automatically_declare_parameters_from_overrides` is `true`
This is the code that declares the parameter `start_type_description_service`.

It uses a try/catch idiom, but does not catches `ParameterAlreadyDeclaredException`.

https://github.com/ros2/rclcpp/blob/7ebc9e4cae34483c8d0510b650032a80ae84fd92/rclcpp/src/rclcpp/node_interfaces/node_type_descriptions.cpp#L70-L84

--------------------

Notice how `use_sim_time` is declared instead:

https://github.com/ros2/rclcpp/blob/7ebc9e4cae34483c8d0510b650032a80ae84fd92/rclcpp/src/rclcpp/time_source.cpp#L254-L274

While `use_sim_time` is checked with `has_parameter()` call for existence, `start_type_description_service` declaration does not.

I believe this is a bug and should be fixed. If maintainers agree, I can open a PR.

BTW, I strongly believe that this kind of "standard node parameters" should share an almost identical way of declaring them, for code commonality.

### PR DESCRIPTION
**Pull request by roncapat**
Closes #2892 by using the same exact strategy for declaring `use_sim_time`.
https://github.com/ros2/rclcpp/blob/7ebc9e4cae34483c8d0510b650032a80ae84fd92/rclcpp/src/rclcpp/time_source.cpp#L254-L274

Tested (you can try to define `start_type_description_service` like so, and pass it to Nav2 bt_navigator or diagnostic_aggregator):
```yaml
/**:
  ros__parameters:
    use_sim_time: false
    start_type_description_service: false
```
whithout the patch, it crashes like https://github.com/ros/diagnostics/issues/519.

- [x] Add test

### Did you use Generative AI?
No

### CODE REVIEW

File: rclcpp/src/rclcpp/node_interfaces/node_type_descriptions.cpp [hunk 1]
```diff
@@ -65,25 +65,24 @@ class NodeTypeDescriptions::NodeTypeDescriptionsImpl
...
-        .set__read_only(true));
-      enabled = enable_param.get<bool>();
-    } catch (const rclcpp::exceptions::InvalidParameterTypeException & exc) {
-      RCLCPP_ERROR(logger_, "%s", exc.what());
-      throw;
+        rclcpp::ParameterValue(true));
+    } else {
+      enable_param = node_parameters->get_parameter(enable_param_name).get_parameter_value();
+    }
+    if (enable_param.get_type() != rclcpp::PARAMETER_BOOL) {
```
Comment (jmachowinski) [inline rclcpp/src/rclcpp/node_interfaces/node_type_descriptions.cpp:83]: The description and the read_only = true are missing.

**Review by jmachowinski — CHANGES_REQUESTED** [review]

File: rclcpp/src/rclcpp/node_interfaces/node_type_descriptions.cpp (hunk 1 above)
Comment (roncapat) [reply rclcpp/src/rclcpp/node_interfaces/node_type_descriptions.cpp:83]: Sure, can add it.

This in turn makes me wonder whether it could be nice to add such attributes also in the "use_sim_time" parameter definition code. IIRC there are not such attributes.

Comment (roncapat) [reply rclcpp/src/rclcpp/node_interfaces/node_type_descriptions.cpp:83]: (not the read only, just the description)

File: rclcpp/src/rclcpp/node_interfaces/node_type_descriptions.cpp [hunk 2]
```diff
@@ -65,25 +65,24 @@ class NodeTypeDescriptions::NodeTypeDescriptionsImpl
...
-        rcl_interfaces::msg::ParameterDescriptor()
-        .set__name(enable_param_name)
-        .set__type(rclcpp::PARAMETER_BOOL)
-        .set__description("Start the ~/get_type_description service for this node.")
-        .set__read_only(true));
-      enabled = enable_param.get<bool>();
-    } catch (const rclcpp::exceptions::InvalidParameterTypeException & exc) {
-      RCLCPP_ERROR(logger_, "%s", exc.what());
-      throw;
+        rclcpp::ParameterValue(true));
```
Comment (roncapat) [inline rclcpp/src/rclcpp/node_interfaces/node_type_descriptions.cpp]:
```suggestion
        rclcpp::ParameterValue(true),
        rcl_interfaces::msg::ParameterDescriptor()
        .set__name(enable_param_name)
        .set__type(rclcpp::PARAMETER_BOOL)
        .set__description("Start the ~/get_type_description service for this node."));
```

File: rclcpp/src/rclcpp/node_interfaces/node_type_descriptions.cpp [hunk 3]
```diff
@@ -65,25 +65,28 @@ class NodeTypeDescriptions::NodeTypeDescriptionsImpl
...
         rcl_interfaces::msg::ParameterDescriptor()
         .set__name(enable_param_name)
         .set__type(rclcpp::PARAMETER_BOOL)
-        .set__description("Start the ~/get_type_description service for this node.")
-        .set__read_only(true));
-      enabled = enable_param.get<bool>();
-    } catch (const rclcpp::exceptions::InvalidParameterTypeException & exc) {
-      RCLCPP_ERROR(logger_, "%s", exc.what());
-      throw;
+        .set__description("Start the ~/get_type_description service for this node."));
```
Comment (roncapat) [inline rclcpp/src/rclcpp/node_interfaces/node_type_descriptions.cpp]:
```suggestion
        .set__description("Start the ~/get_type_description service for this node.")
        .set__read_only(true));
```

**Review by jmachowinski — APPROVED** [review]

**Comment by jmachowinski** [comment]
can you fix the DCO ?  afterwards I will start the CI run.

@fujitatomoya can you have a second look, I seem to miss a lot currently ;-)

File: rclcpp/src/rclcpp/node_interfaces/node_type_descriptions.cpp [hunk 4]
```diff
@@ -65,25 +65,29 @@ class NodeTypeDescriptions::NodeTypeDescriptionsImpl
...
-      RCLCPP_ERROR(logger_, "%s", exc.what());
-      throw;
+    } else {
+      enable_param = node_parameters->get_parameter(enable_param_name).get_parameter_value();
+    }
+    if (enable_param.get_type() != rclcpp::PARAMETER_BOOL) {
+      RCLCPP_ERROR(
+        logger_, "Invalid type '%s' for parameter 'start_type_description_service', should be 'bool'",
+        rclcpp::to_string(enable_param.get_type()).c_str());
+      throw std::invalid_argument("Invalid type for parameter 'start_type_description_service', should be 'bool'");
```
Comment (roncapat) [inline rclcpp/src/rclcpp/node_interfaces/node_type_descriptions.cpp:87]:
```suggestion
      RCLCPP_ERROR(
        logger_,
        "Invalid type '%s' for parameter 'start_type_description_service', should be 'bool'",
        rclcpp::to_string(enable_param.get_type()).c_str());
      throw std::invalid_argument(
        "Invalid type for parameter 'start_type_description_service', should be 'bool'");
```

**Comment by roncapat** [comment]
@jmachowinski linted, squashed and signed. Thank you for the review :)

**Comment by jmachowinski** [comment]
Pulls: ros2/rclcpp#2897
Gist: https://gist.githubusercontent.com/jmachowinski/11e9cd91cc3356d1b1025dbd5477f75e/raw/5329df1d35568b558b8e03f68247f146b458d39f/ros2.repos
BUILD args: 
TEST args: 
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16441
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24238/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18327/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/3673/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/24842/)

File: rclcpp/test/rclcpp/node_interfaces/test_node_type_descriptions.cpp [hunk 5]
```diff
@@ -37,6 +37,18 @@ TEST_F(TestNodeTypeDescriptions, interface_created)
...
+TEST_F(TestNodeTypeDescriptions, automatically_declare_parameters_from_overrides)
+{
+  rclcpp::NodeOptions node_options;
+  node_options.automatically_declare_parameters_from_overrides(true);
+  node_options.append_parameter_override("start_type_description_service", false);
+  ASSERT_NO_THROW(
+  {
+    auto node = std::make_shared<rclcpp::Node>("node", "ns", node_options);
+    (void) node;
+  });
```
Comment (fujitatomoya) [inline rclcpp/test/rclcpp/node_interfaces/test_node_type_descriptions.cpp:49]: implementation looks good to me, i think this is a right thing to do instead of silently allowing the user application to declare `start_type_description_service` in any parameter types.

probably we would want to add the `EXPECT_THROW` with `std::invalid_argument` test case? that is the original problem raised by https://github.com/ros2/rclcpp/issues/2892?

Comment (roncapat) [reply rclcpp/test/rclcpp/node_interfaces/test_node_type_descriptions.cpp:49]: Hi @fujitatomoya,

> probably we would want to add the EXPECT_THROW with std::invalid_argument test case?

Good idea. Will proceed.

> that is the original problem raised by https://github.com/ros2/rclcpp/issues/2892?

Nope, the issue is that when you set `automatically_declare_parameters_from_overrides` to `true`, and you try to set the `start_type_description_service` parameter, you get an unhandled `ParameterAlreadyDeclaredException` exception. That is already covered/demonstrated by the test I added.

Comment (roncapat) [reply rclcpp/test/rclcpp/node_interfaces/test_node_type_descriptions.cpp:49]: See 1fe177f

**Review by fujitatomoya — APPROVED** [review]

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclcpp#2897
Gist: https://gist.githubusercontent.com/fujitatomoya/36059be8eac06e935cd0e300025b59b1/raw/5329df1d35568b558b8e03f68247f146b458d39f/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp
TEST args:  --packages-above rclcpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16446
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24247/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18332/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/3683/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/24847/)

**Comment by roncapat** [comment]
@fujitatomoya please wait, I noticed one thing I still want to fix.
Please have a look at the updated test case.

We get two different exceptions depending on whether we use `automatically_declare_parameters_from_overrides` or not. IMHO we should always throw `InvalidParameterTypeException`. What do you think?

What happens now:
```c++
ASSERT_THROW(
{
  auto node = std::make_shared<rclcpp::Node>("node", "ns", node_options);
  (void) node;
}, rclcpp::exceptions::InvalidParameterTypeException);

ASSERT_THROW(
{
  node_options.automatically_declare_parameters_from_overrides(true);
  auto node = std::make_shared<rclcpp::Node>("node", "ns", node_options);
  (void) node;
}, std::invalid_argument);
```

**Comment by roncapat** [comment]
With c2ca00d, I made both cases `automatically_declare_parameters_from_overrides` (true/false) throw the same exception, and moreover the same exact exception message:
```
parameter 'start_type_description_service' has invalid type: Wrong parameter type,
parameter {start_type_description_service} is of type {bool}, setting it to {string} is not allowed.
```

This message, in one of the two codepaths, is generated by:

https://github.com/ros2/rclcpp/blob/c2ca00de7186b4aea644352a83d6c8e74cb35e6b/rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp#L299-L311

but unfortunately this method is static, so I copied the snipped here inline, so that when I manually throw, the same exact text is generated.

**Review by jmachowinski — APPROVED** [review]

File: rclcpp/src/rclcpp/node_interfaces/node_type_descriptions.cpp [hunk 6]
```diff
@@ -65,25 +65,33 @@ class NodeTypeDescriptions::NodeTypeDescriptionsImpl
...
+      enable_param = node_parameters->get_parameter(enable_param_name).get_parameter_value();
+    }
+    if (enable_param.get_type() != rclcpp::PARAMETER_BOOL) {
+      RCLCPP_ERROR(
+        logger_,
+            "Invalid type '%s' for parameter 'start_type_description_service', should be 'bool'",
+        rclcpp::to_string(enable_param.get_type()).c_str());
+      std::ostringstream ss;
+	    ss << "Wrong parameter type, parameter {" << enable_param_name << "} is of type {bool}, "
+         << "setting it to {" << to_string(enable_param.get_type()).c_str() << "} is not allowed.";
```
Comment (jmachowinski) [inline rclcpp/src/rclcpp/node_interfaces/node_type_descriptions.cpp]:
```suggestion
         << "setting it to {" << to_string(enable_param.get_type()) << "} is not allowed.";
```

**Review by jmachowinski — APPROVED** [review]

**Comment by jmachowinski** [comment]
Pulls: ros2/rclcpp#2897
Gist: https://gist.githubusercontent.com/jmachowinski/5f8b63ffd74b1bd31a130924c950ba83/raw/5329df1d35568b558b8e03f68247f146b458d39f/ros2.repos
BUILD args: 
TEST args: 
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16467
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24272/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18353/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/3706/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/24869/)

**Comment by roncapat** [comment]
@jmachowinski are those unrelated failures, right?

**Comment by roncapat** [comment]
@fujitatomoya @jmachowinski friendly ping on this, is it ok for merge?

**Review by fujitatomoya — APPROVED** [review]
@roncapat thanks for letting me know, lgtm.

**Comment by fujitatomoya** [comment]
@Mergifyio rebase

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclcpp#2897
Gist: https://gist.githubusercontent.com/fujitatomoya/3cb75d1938440af27724a32d32c1fa32/raw/5329df1d35568b558b8e03f68247f146b458d39f/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp
TEST args:  --packages-above rclcpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16500
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24323/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18393/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/3773/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/24903/)

**Comment by fujitatomoya** [comment]
security related failures are unrelated to this PR.

**Comment by fujitatomoya** [comment]
@Mergifyio backport kilted jazzy
