### PR TITLE
Fix: improve exception context for parameter_value_from

### LINKED ISSUE #2916: parameter_map_from should report which name is missing
### Description

I would like improved error messages for missing parameters. Currently I only see "No parameter value set". But I don't know which parameter this applies to. I'm trying to configure Nav2, so this is somewhat of an issue (...).

I tried to find my way around this code base:
In parameter_map.cpp the method parameter_map_from calls parameter_value_from.
That method can throw rclcpp::exceptions::InvalidParameterValueException. The description "No parameter value set" does not describe which parameter was invalid. That could be fixed: In parameter_map_from the c_param_name is known.

Does this sound like a feasible improvement?

### Motivation

I would like to improve debugging of missing parameters.

### Design / Implementation Considerations

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by mleegwt**
## Description
Adds c_param_name to error messages without changing API interface of parameter_value_from.

Fixes #2916 

### Did you use Generative AI?
ChatGPT 4o

### Additional Information

I was missing instructions for testing/building. I'm used to having Github automatically building my repos. But it has been a long while since my last bit of CPP. So please edit/improve before merging if that is required.

### CODE REVIEW

File: rclcpp/src/rclcpp/parameter_map.cpp [hunk 1]
```diff
@@ -81,7 +81,15 @@ rclcpp::parameter_map_from(const rcl_params_t * const c_params, const char * nod
         throw InvalidParametersException(message);
       }
       const rcl_variant_t * const c_param_value = &(c_params_node->parameter_values[p]);
-      params_node.emplace_back(c_param_name, parameter_value_from(c_param_value));
+      rclcpp::ParameterValue value;
```
Comment (fujitatomoya) [inline rclcpp/src/rclcpp/parameter_map.cpp]:
```suggestion
      ParameterValue value;
```

File: rclcpp/src/rclcpp/parameter_map.cpp [hunk 2]
```diff
@@ -81,7 +81,15 @@ rclcpp::parameter_map_from(const rcl_params_t * const c_params, const char * nod
...
+      try {
+        value = parameter_value_from(param);
```
Comment (fujitatomoya) [inline rclcpp/src/rclcpp/parameter_map.cpp]: where is this `param` from?

```suggestion
        value = parameter_value_from(c_param_value);
```

File: rclcpp/src/rclcpp/parameter_map.cpp [hunk 3]
```diff
@@ -81,7 +81,15 @@ rclcpp::parameter_map_from(const rcl_params_t * const c_params, const char * nod
...
+      } catch (const rclcpp::exceptions::InvalidParameterValueException & e) {
+        throw rclcpp::exceptions::InvalidParameterValueException(
```
Comment (fujitatomoya) [inline rclcpp/src/rclcpp/parameter_map.cpp]:
```suggestion
      } catch (const InvalidParameterValueException & e) {
        throw InvalidParameterValueException(
```

**Review by fujitatomoya — COMMENTED** [review]
I think this is reasonable, lgtm with a few comments.

**Comment by mleegwt** [comment]
> I think this is reasonable, lgtm with a few comments.

Thanks! Suggested changes are committed!

File: rclcpp/src/rclcpp/parameter_map.cpp [hunk 4]
```diff
@@ -81,7 +81,15 @@ rclcpp::parameter_map_from(const rcl_params_t * const c_params, const char * nod
...
-      params_node.emplace_back(c_param_name, parameter_value_from(c_param_value));
+      ParameterValue value;
+      try {
+        value = parameter_value_from(c_param_value);
+      } catch (const InvalidParameterValueException & e) {
+        throw InvalidParameterValueException(
+          std::string("parameter_value_from failed for parameter '") +
+          c_param_name + "': " + e.what());
+      }
+      parameters.emplace_back(c_param_name, value);
```
Comment (ahcorde) [inline rclcpp/src/rclcpp/parameter_map.cpp]:
```suggestion
      params_node.emplace_back(c_param_name, value);
```

**Review by ahcorde — CHANGES_REQUESTED** [review]

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
Pulls: ros2/rclcpp#2917
Gist: https://gist.githubusercontent.com/ahcorde/911b6f6be6bfec05de9a4a2ded55e023/raw/7ab37ec02e9f476ea5580ea68a9337fc27f9bee0/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp
TEST args:  --packages-above rclcpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16637
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/24497/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/18553/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/3954/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/25053/)

**Comment by mleegwt** [comment]
@ahcorde What happened to the Windows build?

**Comment by ahcorde** [comment]
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/25058/)

**Comment by mleegwt** [comment]
@ahcorde Thanks! I saw there also is a release that includes this fix already. I love it!
Next stop for me: Updating to rolling from jazzy for my rover setup to allow resolving my original issue.

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport kilted jazzy humble
