### PR TITLE
Resolve startup race condition for sim time

### LINKED ISSUE #595: 'use_sim_time' only works when set dynamically, not through launch parameters
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - source using master ros2.repos file
- Version or commit hash:
  - I'll get this if you need it
- DDS implementation:
  - Fast-RTPS (default)
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

Launch file:
```
from launch import LaunchDescription

import launch.actions
import launch_ros.actions


def generate_launch_description():
    return LaunchDescription([

        launch.actions.ExecuteProcess(
            cmd=['gzserver', '--verbose', '-s', 'libgazebo_ros_init.so', 'empty.world'],
            output='screen'),

        launch_ros.actions.Node(
            package='testpackage',
            node_executable='testpackage',
            node_name='minimal_subscriber',
            output='screen',
            parameters=[{'use_sim_time': True}])
    ])
```
Source file:
```
#include <memory>
#include <exception>
#include "rclcpp/rclcpp.hpp"

int main(int argc, char ** argv)
{
  rclcpp::init(argc, argv);
  try {
    auto node=rclcpp::Node::make_shared("minimal_subscriber");
    rclcpp::Rate loop_rate(1);
    while(rclcpp::ok()) {
      RCLCPP_INFO(node->get_logger(), "Node Time is %ld", node->now().nanoseconds());
      RCLCPP_INFO(node->get_logger(), "Clock Time is %ld", rclcpp::Clock(RCL_ROS_TIME).now().nanoseconds());
      rclcpp::spin_some(node);
      loop_rate.sleep();
    }
  } catch (...) {
    std::cerr << "caught exception" << std::endl;
  }
  rclcpp::shutdown();


  return 0;
}
```
#### Expected behavior
When I set 'use_sim_time' through a launch file, it should start using the simulation clock from gazebo as soon as it is available. This is seen in the output below as 'Node Time'

#### Actual behavior
The node won't actually switch to sim time unless use_sim_time is set dynamically after the node has launched. 

#### Additional information
```
mkhansen@mkhansen-desk:~/ros2_dev/navigation2_ws$ ros2 launch testpackage testpackage_launch.py
[INFO] [launch]: process[gzserver-1]: started with pid [26616]
[INFO] [launch]: process[testpackage-2]: started with pid [26617]
[INFO] [minimal_subscriber]: Node Time is 1543457809023725948
[INFO] [minimal_subscriber]: Clock Time is 1543457809023744824
Gazebo multi-robot simulator, version 9.0.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 10.7.201.25
[Err] [RenderEngine.cc:725] Can't open display:
[Wrn] [RenderEngine.cc:93] Unable to create X window. Rendering will be disabled
[Wrn] [RenderEngine.cc:293] Cannot initialize render engine since render path type is NONE. Ignore this warning ifrendering has been turned off on purpose.
[Err] [Server.cc:379] Could not open file[empty.world]
[Wrn] [Server.cc:338] Falling back on worlds/empty.world
[INFO] [minimal_subscriber]: Node Time is 1543457810023793285
[INFO] [minimal_subscriber]: Clock Time is 1543457810023806356
[INFO] [minimal_subscriber]: Node Time is 1543457811023812189
[INFO] [minimal_subscriber]: Clock Time is 1543457811023822896
[INFO] [minimal_subscriber]: Node Time is 1543457812023810425
[INFO] [minimal_subscriber]: Clock Time is 1543457812023822080
[INFO] [minimal_subscriber]: Node Time is 1543457813023811638
[INFO] [minimal_subscriber]: Clock Time is 1543457813023824679
[INFO] [minimal_subscriber]: Node Time is 1543457814023787142
[INFO] [minimal_subscriber]: Clock Time is 1543457814023800707
[INFO] [minimal_subscriber]: Node Time is 1543457815023810150
[INFO] [minimal_subscriber]: Clock Time is 1543457815023821468
[INFO] [minimal_subscriber]: Node Time is 1543457816023783249
[INFO] [minimal_subscriber]: Clock Time is 1543457816023795940
[INFO] [minimal_subscriber]: Node Time is 1543457817023781949
[INFO] [minimal_subscriber]: Clock Time is 1543457817023793476
[INFO] [minimal_subscriber]: Node Time is 1543457818023808947
[INFO] [minimal_subscriber]: Clock Time is 1543457818023820761
[INFO] [minimal_subscriber]: Node Time is 1543457819023784617
[INFO] [minimal_subscriber]: Clock Time is 1543457819023798860
[INFO] [minimal_subscriber]: Node Time is 1543457820023815570
[INFO] [minimal_subscriber]: Clock Time is 1543457820023829309
[INFO] [minimal_subscriber]: Node Time is 1543457821023812025
[INFO] [minimal_subscriber]: Clock Time is 1543457821023824201
[INFO] [minimal_subscriber]: Node Time is 1543457822023811756
[INFO] [minimal_subscriber]: Clock Time is 1543457822023824277
[INFO] [minimal_subscriber]: Node Time is 1543457823023811181
[INFO] [minimal_subscriber]: Clock Time is 1543457823023824359
[INFO] [minimal_subscriber]: Node Time is 1543457824023806113
[INFO] [minimal_subscriber]: Clock Time is 1543457824023818997
[INFO] [minimal_subscriber]: Node Time is 1543457825023780745
[INFO] [minimal_subscriber]: Clock Time is 1543457825023792874
[INFO] [minimal_subscriber]: Node Time is 1543457826023785984
[INFO] [minimal_subscriber]: Clock Time is 1543457826023799544
[INFO] [minimal_subscriber]: Node Time is 1543457827023784097
[INFO] [minimal_subscriber]: Clock Time is 1543457827023795893
[INFO] [minimal_subscriber]: Node Time is 1543457828023810237
[INFO] [minimal_subscriber]: Clock Time is 1543457828023824484
[INFO] [minimal_subscriber]: Node Time is 1543457829023804999
[INFO] [minimal_subscriber]: Clock Time is 1543457829023820734
[INFO] [minimal_subscriber]: Node Time is 1543457830023813067
[INFO] [minimal_subscriber]: Clock Time is 1543457830023825471
[INFO] [minimal_subscriber]: Node Time is 1543457831023804823
[INFO] [minimal_subscriber]: Clock Time is 1543457831023817486
[INFO] [minimal_subscriber]: Node Time is 1543457832023810373
[INFO] [minimal_subscriber]: Clock Time is 1543457832023820863
[INFO] [minimal_subscriber]: Node Time is 1543457833023812489
[INFO] [minimal_subscriber]: Clock Time is 1543457833023824741
[INFO] [minimal_subscriber]: Node Time is 0
[INFO] [minimal_subscriber]: Clock Time is 1543457834023820720
[INFO] [minimal_subscriber]: Node Time is 24576000000
[INFO] [minimal_subscriber]: Clock Time is 1543457835023791415
[INFO] [minimal_subscriber]: Node Time is 25581000000
[INFO] [minimal_subscriber]: Clock Time is 1543457836023819240
[INFO] [minimal_subscriber]: Node Time is 26584000000
[INFO] [minimal_subscriber]: Clock Time is 1543457837023795041
[INFO] [minimal_subscriber]: Node Time is 27588000000
[INFO] [minimal_subscriber]: Clock Time is 1543457838023820281
[INFO] [minimal_subscriber]: Node Time is 28589000000
[INFO] [minimal_subscriber]: Clock Time is 1543457839023821805
[INFO] [minimal_subscriber]: Node Time is 29492000000
[INFO] [minimal_subscriber]: Clock Time is 1543457840023791436
[INFO] [minimal_subscriber]: Node Time is 30497000000
[INFO] [minimal_subscriber]: Clock Time is 1543457841023795913
[INFO] [minimal_subscriber]: Node Time is 31500000000
[INFO] [minimal_subscriber]: Clock Time is 1543457842023852300
[INFO] [minimal_subscriber]: Node Time is 32503000000
[INFO] [minimal_subscriber]: Clock Time is 1543457843023825404
[INFO] [minimal_subscriber]: Node Time is 33505000000
[INFO] [minimal_subscriber]: Clock Time is 1543457844023821935
[INFO] [minimal_subscriber]: Node Time is 34509000000
[INFO] [minimal_subscriber]: Clock Time is 1543457845023784820
[INFO] [minimal_subscriber]: Node Time is 35511000000
[INFO] [minimal_subscriber]: Clock Time is 1543457846023825233
```
Here you can see the parameter was set already by the launch file, thus the param 'get' returned True. But the node time didn't change until I set it a 2nd time dynamically.
```
mkhansen@mkhansen-desk:~/ros2_dev/navigation2_ws$ ros2 param get /minimal_subscriber use_sim_time
Boolean value is: True
mkhansen@mkhansen-desk:~/ros2_dev/navigation2_ws$ ros2 param get /minimal_subscriber use_sim_time
Boolean value is: True
mkhansen@mkhansen-desk:~/ros2_dev/navigation2_ws$ ros2 param set /minimal_subscriber use_sim_time True
Set parameter successful
```
Credit to @crdelsey who helped to find / isolate this bug and wrote the test node

### PR DESCRIPTION
**Pull request by tfoote**
Fixes #595 

A race condition at startup was identified in #595 where the clock and parameter interfaces needed each other to initialize and since they could not rely on both being initialized the loop was closed through sending and receiving ROS messages. This however meant that initialization was dependent on messages being passed through ROS topics before time would be initialized correctly. The solution to this is to break apart the clock dependency into the time source and clock separately, like we already do for the underlying data and this breaks the cycle.

When reviewing this there's an extension which would be a good improvement to not rely on parameter events being published but use the internal node interface API to get the events in a callback. However as we're late in the release cycle I'm going to hold off on fixing that is this is functional just not optimal and would require a noteably large API change. Along with that change if there was a more fully featured API for registering callbacks for parameter changes locally, the parameter event publishing could also be split out into a separate component that could obviate the need for a parameter to turn that functionality on and off in the constructor of the parameter, and avoid the dependencies on the clock and topics interface for the core parameter API.

### CODE REVIEW

**Comment by tfoote** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5860/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2416/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4848/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5750/)

File: rclcpp/include/rclcpp/node_interfaces/node_time_source.hpp [hunk 1]
```diff
@@ -0,0 +1,72 @@
+// Copyright 2017 Open Source Robotics Foundation, Inc.
```
Comment (wjwwood) [inline rclcpp/include/rclcpp/node_interfaces/node_time_source.hpp]:
```suggestion
// Copyright 2018 Open Source Robotics Foundation, Inc.
```

File: rclcpp/include/rclcpp/node_interfaces/node_time_source_interface.hpp [hunk 2]
```diff
@@ -0,0 +1,38 @@
+// Copyright 2017 Open Source Robotics Foundation, Inc.
```
Comment (wjwwood) [inline rclcpp/include/rclcpp/node_interfaces/node_time_source_interface.hpp]:
```suggestion
// Copyright 2018 Open Source Robotics Foundation, Inc.
```

File: rclcpp/src/rclcpp/time_source.cpp [hunk 3]
```diff
@@ -53,25 +53,48 @@ void TimeSource::attachNode(rclcpp::Node::SharedPtr node)
...
+      }
+    } else {
+      RCLCPP_ERROR(logger_, "Invalid type for parameter 'use_sim_time' %s should be bool",
+        use_sim_time_param.get_type_name());
+    }
+  } else {
+    RCLCPP_DEBUG(logger_, "'use_sim_time' parameter not set, using wall time by default.");
+  }
+
+  // TODO(tfoote) use parameters interface not subscribe
```
Comment (wjwwood) [inline rclcpp/src/rclcpp/time_source.cpp]: What does this comment mean? Where is "subscribe" used?

Comment (tfoote) [reply rclcpp/src/rclcpp/time_source.cpp]: This is referring to #609 I added it to the comment.

**Comment by tfoote** [comment]
Resolved comments and rerunning CI for mac and windows. The windows tests looked to be a bunch from other issues.

* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4859/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5764/)

@ros-pull-request-builder retest this please

**Comment by chapulina** [comment]
The original sim time test in `gazebo_ros_pkgs` passes all expectations for me with this branch, but it hangs in the end after printing `free(): invalid pointer`, which doesn't happen with this repo's `master` branch.

**Comment by chapulina** [comment]
After debugging a bit with @tfoote, it looks that my problem may be coming from having `rclcpp` both from debs and from source installed, so they may be conflicting with each other. We ran the exact same test under `gazebo_ros_pkgs` and under `rclcpp`, and during the latter nothing bad happens, which suggests the issue is in how `gazebo_ros_pkgs` is being compiled against `rclcpp`.

I'll make a PR changing the sim time test to work with this and we can run CI with the combination.

**Comment by tfoote** [comment]
This PR has been tested as working against the new navigation stack by @crdelsey https://github.com/ros2/rclcpp/issues/595#issuecomment-446317575

File: rclcpp/src/rclcpp/node_interfaces/node_time_source.cpp [hunk 4]
```diff
@@ -0,0 +1,50 @@
+// Copyright 2017 Open Source Robotics Foundation, Inc.
```
Comment (sloretz) [inline rclcpp/src/rclcpp/node_interfaces/node_time_source.cpp]: 2018?

File: rclcpp/include/rclcpp/node_interfaces/node_time_source_interface.hpp [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+#include "rclcpp/macros.hpp"
+#include "rclcpp/visibility_control.hpp"
+
+namespace rclcpp
+{
+namespace node_interfaces
+{
+
+/// Pure virtual interface class for the NodeTimeSource part of the Node API.
+class NodeTimeSourceInterface
```
Comment (sloretz) [inline rclcpp/include/rclcpp/node_interfaces/node_time_source_interface.hpp]: I think this might need a virtual destructor to make sure `~NodeTimeSource()` gets called when the `std::shared_ptr<NodeTimeSourceInterface>` on the node is destructed.

Comment (tfoote) [reply rclcpp/include/rclcpp/node_interfaces/node_time_source_interface.hpp]: Yeah, this is probably true as well for all the other interface classes too. I went over it with @wjwwood and it looks like virtual default constructors are the best approch. We're clearly not using it right now but in the future not having them will cause warnings or errors.

**Comment by tfoote** [comment]
Added virtual destructors for all interfaces in a7de819473ab3b3e28faa8041e777eeaffaece92
Rerunning CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5881/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2431/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4864/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5772/)

File: rclcpp/include/rclcpp/node_interfaces/node_base_interface.hpp [hunk 6]
```diff
@@ -138,6 +138,10 @@ class NodeBaseInterface
   virtual
   std::unique_lock<std::recursive_mutex>
   acquire_notify_guard_condition_lock() const = 0;
+
+  RCLCPP_PUBLIC
+  virtual
+  ~NodeBaseInterface() = default;
```
Comment (wjwwood) [inline rclcpp/include/rclcpp/node_interfaces/node_base_interface.hpp]: The destructor is conventionally at the top of the class just after any constructors.

**Comment by tfoote** [comment]
Retrying windows after merging refactor

* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5​78​3/)

File: rclcpp/src/rclcpp/node_interfaces/node_time_source.cpp (hunk 4 above)
Comment (Karsten1987) [reply rclcpp/src/rclcpp/node_interfaces/node_time_source.cpp]: this could probably still be fixed

**Comment by tfoote** [comment]
@ros-pull-request-builder retest this please
