### PR TITLE
publish_feedback should effect only on executing state.

### LINKED ISSUE #3117: `ServerGoalHandle::publish_feedback()` does not enforce precondition that goal must be in EXECUTING state
### Generated by Generative AI

_No response_

### Operating System:

```Linux tomoyafujita-B760M-Pro-RS-D4 6.17.0-19-generic #19~24.04.2-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar  6 23:08:46 UTC 2 x86_64 x86_64 x86_64 GNU/Linux```

### ROS version or commit hash:

ros rolling source build

### RMW implementation (if applicable):

_No response_

### RMW Configuration (if applicable):

_No response_

### Client library (if applicable):

rclcpp

### 'ros2 doctor --report' output

<details><summary>ros2 doctor --report</summary>

```console
<COPY OUTPUT HERE>
```
</details>

### Steps to reproduce issue

`ServerGoalHandle::publish_feedback()` does not enforce documented precondition that goal must be in EXECUTING state.
ServerGoalHandle::publish_feedback() documents that it must only be called when the goal is executing and claims to throw std::runtime_error if the goal is in any other state (rclcpp). However, rclcpp (nor rclpy) enforces this precondition at runtime. After calling a terminal state method (succeed(), abort(), or canceled()), publish_feedback() silently publishes feedback on the /_action/feedback topic, and clients can receive it.
This violates the documented API contract and can lead to confusing behavior in applications that assume the action lifecycle is enforced by the library.

### Expected behavior

After calling goal_handle->succeed(result) (or abort() / canceled()), any subsequent call to goal_handle->publish_feedback(feedback) should either:

- Throw an exception / raise an error (consistent with the rclcpp Doxygen documentation which states "throws std::runtime_error if the goal is in any state besides executing"), or
- Be silently ignored with a warning log, or
- At minimum, log a warning indicating the feedback was published after the goal reached a terminal state.

The current rclcpp documentation already promises option (1), but it is not implemented.

### Actual behavior

No state check is performed at this level

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by fujitatomoya**
## Description

Closes https://github.com/ros2/rclcpp/issues/3117

### Is this user-facing behavior change?

Yes, only warning is going to be popped up that tells user application `publish_feedback` can be effective only executing state.

### Did you use Generative AI?

No

### CODE REVIEW

File: rclcpp_action/include/rclcpp_action/server_goal_handle.hpp [hunk 1]
```diff
@@ -151,13 +151,20 @@ class ServerGoalHandle : public ServerGoalHandleBase
    * If execution of a goal is deferred then `ServerGoalHandle::set_executing()` must be called
    * first.
    *
-   * \throws std::runtime_error If the goal is in any state besides executing.
```
Comment (fujitatomoya) [inline rclcpp_action/include/rclcpp_action/server_goal_handle.hpp:154]: i was going to honor this original design behavior, but this could be a bit surprising for user application. so this PR only prints the warning that instead.

**Review by ahcorde — APPROVED** [review]

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclcpp#3118
Gist: https://gist.githubusercontent.com/fujitatomoya/d6cdd9c1593d2a24a4e7eba4f190264c/raw/5d1301a472c408d21d17f962af36ab4a9825a182/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp_action
TEST args:  --packages-above rclcpp_action
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/18749
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/28431/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/21300/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/8286/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/27303/)

**Comment by jmachowinski** [comment]
Was that actually throwing before ?
I would prefer a throw there, as this trying to publish feedback after the goal was closed is a clear logic programming error.

**Comment by fujitatomoya** [comment]
@jmachowinski no it was never implemented in that way... even though doc section defines that behavior.

i was going to that way, but my though is that would be kinda surprising...

**Comment by jmachowinski** [comment]
Judging from our own stack, warnings get ignored, as they are in the general console spam. 
Exceptions get fixed... I can't think of a scenario were sending feedback after sending the goal result is correct. Especially as the doc already mentioned it, the exception seems more as the way to go...

**Comment by fujitatomoya** [comment]
i will go ahead to merge this, if necessary, we can enforce the exception after some period that prints the warning.
