### PR TITLE
Broken promise

### LINKED ISSUE #44: Fix 'broken promise' error in parameter client

### PR DESCRIPTION
**Pull request by esteve**
This PR makes sure that promises are not destroyed too early, adds more cases to the list_parameters verb and fixes the parameters service to listen on the appropriate topic.

Fixes #44

### CODE REVIEW

File: rclcpp/include/rclcpp/node_impl.hpp [hunk 1]
```diff
@@ -356,7 +356,9 @@ Node::list_parameters(
   // TODO(esteve): define parameter separator, use "." for now
   for (auto & kv : parameters_) {
     if (std::any_of(prefixes.cbegin(), prefixes.cend(), [&kv, &depth](const std::string & prefix) {
-      if (kv.first.find(prefix + ".") == 0) {
+      if (kv.first == prefix) {
+        return true;
+      } else  if (kv.first.find(prefix + ".") == 0) {
```
Comment (wjwwood) [inline rclcpp/include/rclcpp/node_impl.hpp]: Looks like there are two spaces between `else` and `if`, is that intentional?

**Comment by esteve** [comment]
Don't review yet.

File: rclcpp/include/rclcpp/node_impl.hpp (hunk 1 above)
Comment (esteve) [inline rclcpp/include/rclcpp/node_impl.hpp]: I haven't run uncrustify yet, will do in a moment.

File: rclcpp/include/rclcpp/parameter_client.hpp [hunk 2]
```diff
@@ -73,28 +74,30 @@ class AsyncParametersClient
...
             parameter.name = names[i];
             parameter.value = pvalue;
-            return rclcpp::parameter::ParameterVariant::from_parameter(parameter);
-          });
-          promise_result.set_value(parameter_variants);
+            parameter_variants.push_back(rclcpp::parameter::ParameterVariant::from_parameter(parameter));
+          }
+
+          promise_result->set_value(parameter_variants);
+          get_parameters_promises_.erase(promise_result);
```
Comment (wjwwood) [inline rclcpp/include/rclcpp/parameter_client.hpp]: Can you prefix this with `this->`? I had trouble matching the use of `this` in the lambda to a specific line.

Comment (wjwwood) [inline rclcpp/include/rclcpp/parameter_client.hpp]: Same thing in a few places below.

File: rclcpp/include/rclcpp/parameter_client.hpp [hunk 3]
```diff
@@ -241,6 +253,12 @@ class AsyncParametersClient
   rclcpp::client::Client<rcl_interfaces::srv::DescribeParameters>::SharedPtr
     describe_parameters_client_;
   std::string remote_node_name_;
+
+  std::unordered_set<std::shared_ptr<std::promise<std::vector<rclcpp::parameter::ParameterVariant>>>> get_parameters_promises_;
+  std::unordered_set<std::shared_ptr<std::promise<std::vector<rclcpp::parameter::ParameterType>>>> get_parameter_types_promises_;
+  std::unordered_set<std::shared_ptr<std::promise<std::vector<rcl_interfaces::msg::SetParametersResult>>>> set_parameters_promises_;
+  std::unordered_set<std::shared_ptr<std::promise<rcl_interfaces::msg::SetParametersResult>>> set_parameters_atomically_promises_;
+  std::unordered_set<std::shared_ptr<std::promise<rcl_interfaces::msg::ListParametersResult>>> list_parameters_promises_;
```
Comment (wjwwood) [inline rclcpp/include/rclcpp/parameter_client.hpp]: Can you break these into multi line statements? These lines are over 120 characters long.

Comment (wjwwood) [inline rclcpp/include/rclcpp/parameter_client.hpp]: Or use typedefs.

**Comment by wjwwood** [comment]
Oh, sorry, I just assumed.

It actually looks good to me, other than the minor style comments.

**Comment by esteve** [comment]
Linux buildfarm:

http://54.183.26.131:8080/view/ros2/job/ros2_batch_ci_linux/161/

**Comment by esteve** [comment]
@wjwwood no worries! :-) I noticed I hadn't run uncrustify before submitting the PR.

**Comment by esteve** [comment]
Please review.

File: rclcpp/include/rclcpp/node_impl.hpp [hunk 4]
```diff
@@ -367,11 +369,13 @@ Node::list_parameters(
...
       size_t last_separator = kv.first.find_last_of('.');
-      std::string prefix = kv.first.substr(0, last_separator);
-      if (std::find(result.prefixes.cbegin(), result.prefixes.cend(),
-        prefix) == result.prefixes.cend())
-      {
-        result.prefixes.push_back(prefix);
+      if (std::string::npos != last_separator) {
+        std::string prefix = kv.first.substr(0, last_separator);
+        if (std::find(result.prefixes.cbegin(), result.prefixes.cend(),
+          prefix) == result.prefixes.cend())
```
Comment (dirk-thomas) [inline rclcpp/include/rclcpp/node_impl.hpp]: I found reading this line pretty difficult due to the wrapping within the `find` call. Wrapping after the comparison operator `==` helped me to parse the line.

File: rclcpp/include/rclcpp/parameter_client.hpp [hunk 5]
```diff
@@ -73,28 +74,32 @@ class AsyncParametersClient
...
+    get_parameters_promises_.insert(promise_result);
+    auto future_result = promise_result->get_future().share();
 
     auto request = std::make_shared<rcl_interfaces::srv::GetParameters::Request>();
     request->names = names;
 
     get_parameters_client_->async_send_request(
       request,
-      [&names, &promise_result, &future_result, &callback](
+      [names, promise_result, &future_result, &callback, this](
```
Comment (dirk-thomas) [inline rclcpp/include/rclcpp/parameter_client.hpp]: What is `this` used for in the lambda function? Should the lambda body use `this` explicitly to make it more visible? Or instead should other variables being specified in the capture list?

File: rclcpp/include/rclcpp/node_impl.hpp (hunk 4 above)
Comment (wjwwood) [inline rclcpp/include/rclcpp/node_impl.hpp]: I also had trouble with that line, but I wasn't sure what to suggest at the time. I think that this is only slightly more readable:

```c++
        if (std::find(result.prefixes.cbegin(), result.prefixes.cend(), prefix) ==
          result.prefixes.cend())
        {
          /* stuff... */
        }
```

File: rclcpp/include/rclcpp/parameter_client.hpp (hunk 5 above)
Comment (wjwwood) [inline rclcpp/include/rclcpp/parameter_client.hpp]: https://github.com/ros2/rclcpp/pull/47#discussion_r33105609

File: rclcpp/include/rclcpp/parameter_client.hpp (hunk 3 above)
Comment (esteve) [inline rclcpp/include/rclcpp/parameter_client.hpp]: Fixed.

File: rclcpp/include/rclcpp/node_impl.hpp (hunk 4 above)
Comment (esteve) [inline rclcpp/include/rclcpp/node_impl.hpp]: Done.

File: rclcpp/include/rclcpp/parameter_client.hpp (hunk 5 above)
Comment (wjwwood) [inline rclcpp/include/rclcpp/parameter_client.hpp]: I made a note about the same thing in my branch that I pushed (which was when me and @esteve were hacking on it together):

https://github.com/ros2/rclcpp/commit/c6afe5c4d858a12f188c4c5334b9cef5f52977f6#diff-3d5a5b02e888be31f79e8c934aab2847R163

I'm not sure what to do about it, but it at least deserves a TODO so we don't forget about it. Maybe it should be handled by a weak pointer and `std::enable_shared_from_this`?

Comment (esteve) [inline rclcpp/include/rclcpp/parameter_client.hpp]: @dirk-thomas good catch about the life time of `this`. Fixed.

File: rclcpp/include/rclcpp/parameter_client.hpp [hunk 6]
```diff
@@ -73,28 +75,33 @@ class AsyncParametersClient
...
-    auto future_result = promise_result.get_future().share();
+    auto promise_result =
+      std::make_shared<std::promise<std::vector<rclcpp::parameter::ParameterVariant>>>();
+    this->get_parameters_promises_.insert(promise_result);
+    auto future_result = promise_result->get_future().share();
 
     auto request = std::make_shared<rcl_interfaces::srv::GetParameters::Request>();
     request->names = names;
 
+    auto self = shared_from_this();
```
Comment (wjwwood) [inline rclcpp/include/rclcpp/parameter_client.hpp]: This will only work if the instance is already owned by another `shared_ptr` right? Do we make that guarantee?

File: rclcpp/include/rclcpp/parameter_client.hpp [hunk 7]
```diff
@@ -73,28 +75,33 @@ class AsyncParametersClient
     std::function<void(
       std::shared_future<std::vector<rclcpp::parameter::ParameterVariant>>)> callback = nullptr)
   {
-    std::promise<std::vector<rclcpp::parameter::ParameterVariant>> promise_result;
-    auto future_result = promise_result.get_future().share();
+    auto promise_result =
+      std::make_shared<std::promise<std::vector<rclcpp::parameter::ParameterVariant>>>();
+    this->get_parameters_promises_.insert(promise_result);
```
Comment (dirk-thomas) [inline rclcpp/include/rclcpp/parameter_client.hpp]: I don't think `this` is necessary here since the usage is not in a lambda.

Same for some of the below cases.

File: rclcpp/include/rclcpp/parameter_client.hpp (hunk 5 above)
Comment (dirk-thomas) [inline rclcpp/include/rclcpp/parameter_client.hpp]: I would propose to create a test for exactly this case.

File: rclcpp/include/rclcpp/parameter_client.hpp (hunk 7 above)
Comment (esteve) [inline rclcpp/include/rclcpp/parameter_client.hpp]: I just added it to make the code more consistent, since `this` wasn't necessary in the lambda either.

File: rclcpp/include/rclcpp/parameter_client.hpp (hunk 6 above)
Comment (esteve) [inline rclcpp/include/rclcpp/parameter_client.hpp]: I'm reworking this, I'll change switch the sets to shared pointers and just pass them down to the lambda.

Comment (esteve) [inline rclcpp/include/rclcpp/parameter_client.hpp]: Forget what I said, this won't work.

**Comment by esteve** [comment]
Linux buildfarm:

http://54.183.26.131:8080/view/ros2/job/ros2_batch_ci_linux/164/

**Comment by esteve** [comment]
Linux buildfarm:

http://54.183.26.131:8080/view/ros2/job/ros2_batch_ci_linux/165/

**Comment by tfoote** [comment]
+1

**Comment by dirk-thomas** [comment]
+1 (please squash before merge)

**Comment by esteve** [comment]
I made a few more changes to avoid storing the promises in the `AsyncParametersClient` instance and to prevent `std::shared_future` instances from being destroyed prematurely.

**Comment by jacquelinekay** [comment]
Waiting on the next [Linux Jenkins results](http://54.183.26.131:8080/view/ros2/job/ros2_batch_ci_linux/166/) before I approve.

**Comment by esteve** [comment]
Linux buildfarm:

http://54.183.26.131:8080/view/ros2/job/ros2_batch_ci_linux/166/

**Comment by tfoote** [comment]
Much simpler +1. 

PS @wjwwood now has the new dedicated buildfarm running for ROS 2.0 The job has the same output here: http://ci.ros2.org/job/ros2_batch_ci_linux/8/
http://ci.ros2.org/job/ros2_batch_ci_linux/9 has the fix for https://github.com/ament/ament_lint/issues/24

**Comment by wjwwood** [comment]
+1

**Comment by esteve** [comment]
Rebased against master and squashed the last changes. This builds find, @jacquelinekay could you give a final review on this? Thanks!

**Comment by jacquelinekay** [comment]
+1. looks good to me. I haven't followed the evolution of the issue/the solution and I don't have a lot of experience using `std::promise` and `std::future`, so I learned a bit from reviewing this.

**Comment by esteve** [comment]
Thanks everybody for going through this long PR
