### PR TITLE
Remove fixed guard conditions, add notify guard conditions

### LINKED ISSUE #209: wake up spin when new waitable things are added to a node
For example:

```c++
auto node = rclcpp::Node::make_shared("node_name");
rclcpp::executors::SingleThreadedExecutor executor;
executor.add_node(node);
std::thread spin_thread([&executor]() {executor.spin();});
auto timer = node->create_timer([]() {printf("hello world\n");});
spin_thread.join();
```

This code may never print "hello world" if the spin call starts before the timer is created. So to fix this, any time something that is affected by spinning is added to a node, spin should be woken up so that it can consider new work.

To accomplish this, each node will probably need a new guard condition which is triggered any time something new is added that needs to wake up spin. This would probably include subscriptions, timers, service servers or clients, and parameter servers or clients.

### PR DESCRIPTION
**Pull request by jacquelinekay**
Fixes #209 
also connects to ros2/rcl#33

### CODE REVIEW

File: rclcpp/src/rclcpp/node.cpp [hunk 1]
```diff
@@ -36,7 +36,8 @@ Node::Node(
   bool use_intra_process_comms)
 : name_(node_name), context_(context),
   number_of_subscriptions_(0), number_of_timers_(0), number_of_services_(0),
-  use_intra_process_comms_(use_intra_process_comms)
+  use_intra_process_comms_(use_intra_process_comms),
+  notify_guard_condition_(rmw_create_guard_condition())
```
Comment (dirk-thomas) [inline rclcpp/src/rclcpp/node.cpp]: Where is this being deallocated?

Comment (jacquelinekay) [inline rclcpp/src/rclcpp/node.cpp]: ah, yeah, I have to add a custom destructor for Node now.

Comment (wjwwood) [inline rclcpp/src/rclcpp/node.cpp]: What if `rmw_create_guard_condition()` returns `nullptr` (fails)?

Comment (jacquelinekay) [inline rclcpp/src/rclcpp/node.cpp]: Does 9dc89bb answer these questions?

Comment (wjwwood) [inline rclcpp/src/rclcpp/node.cpp]: Lgtm.

**Comment by wjwwood** [comment]
+1

**Comment by jacquelinekay** [comment]
I think this is good now. I changed some stuff since @wjwwood gave a +1 so you may want to re-review.

http://ci.ros2.org/job/ci_linux/1126/
http://ci.ros2.org/job/ci_osx/912/ (ran with `repeat-until-fail 20` so it's taking a while, but I wanted to catch any flaky regressions)
http://ci.ros2.org/job/ci_windows/1194/

File: rclcpp/include/rclcpp/node_impl.hpp [hunk 2]
```diff
@@ -134,6 +134,11 @@ Node::create_publisher(
       shared_publish_callback,
       intra_process_publisher_handle);
   }
+  if (rmw_trigger_guard_condition(notify_guard_condition_) != RMW_RET_OK) {
+    throw std::runtime_error(
+            std::string(
+              "Failed to notify waitset of change to node state: ") + rmw_get_error_string());
```
Comment (dirk-thomas) [inline rclcpp/include/rclcpp/node_impl.hpp]: Would it be helpful to customize the following error message to mention how the node state changed in order to distinguish them in case they happen?

Comment (jacquelinekay) [inline rclcpp/include/rclcpp/node_impl.hpp]: That's a good idea. I changed the error messages to the format "Failed to notify waitset on X creation" in ddc6609, where X is the type of entity added to the node.

**Comment by jacquelinekay** [comment]
this has sat for a while so I'm going to merge soon unless there are objections.

**Comment by wjwwood** [comment]
It's in "in progress"?

I plus ones it before, so it should be fine. You were just fixing up tests right?

**Comment by jacquelinekay** [comment]
Yeah... I think the label is a Waffle/Github sync bug. Not sure about that.
