### PR TITLE
clear handles before node destruction in test_memory_strategy.

### LINKED ISSUE #2968: 🧑‍🌾  `rclcpp.test_memory_strategy` returns -11 in CI
### Generated by Generative AI

_No response_

### Operating System:

Linux arrch64, rhel and win

### ROS version or commit hash:

Rolling

### RMW implementation (if applicable):

_No response_

### RMW Configuration (if applicable):

_No response_

### Client library (if applicable):

_No response_

### 'ros2 doctor --report' output

_No response_

### Steps to reproduce issue

1. Run a build in any of the jobs mentioned below
2. See tests fail

### Expected behavior

Test should pass

### Actual behavior

Test is failing

### Additional information

Reference builds:
- [Rci__nightly-connext_ubuntu_noble_amd64#558](http://build.ros2.org/job/Rci__nightly-connext_ubuntu_noble_amd64/558)
- [nightly_linux-aarch64_debug#3301](https://ci.ros2.org/job/nightly_linux-aarch64_debug/3301)
- [nightly_linux-aarch64_release#3291](https://ci.ros2.org/job/nightly_linux-aarch64_release/3291)
- [nightly_linux-aarch64_repeated#3324](https://ci.ros2.org/job/nightly_linux-aarch64_repeated/3324)
- [nightly_linux-rhel_release#2421](https://ci.ros2.org/job/nightly_linux-rhel_release/2421)
- [nightly_linux-rhel_repeated#2430](https://ci.ros2.org/job/nightly_linux-rhel_repeated/2430)
- [nightly_win_rel#3582](https://ci.ros2.org/job/nightly_win_rel/3582)
- [nightly_win_rep#3885](https://ci.ros2.org/job/nightly_win_rep/3885)

Flakyness:
job_name|last_fail|first_fail|build_count|failure_count|failure_percentage
-- | -- | -- | -- | -- | --
nightly_linux-aarch64_repeated|2025-10-16|2025-10-03|14|10|71.43
nightly_linux-aarch64_release|2025-10-16|2025-10-09|16|7|43.75
nightly_linux-aarch64_debug|2025-10-16|2025-10-09|16|8|50.0
Rci__nightly-connext_ubuntu_noble_amd64|2025-10-15|2025-10-15|15|1|6.67
nightly_win_rel|2025-10-14|2025-10-14|16|1|6.25
nightly_win_rep|2025-10-11|2025-10-03|14|2|14.29
nightly_linux-rhel_repeated|2025-10-03|2025-10-03|16|1|6.25
nightly_linux-rhel_release|2025-10-03|2025-10-03|16|1|6.25

Log output:
```
-- run_test.py: invoking following command in '/home/jenkins-agent/workspace/nightly_linux-aarch64_repeated/ws/build/rclcpp/test/rclcpp':
 - /home/jenkins-agent/workspace/nightly_linux-aarch64_repeated/ws/build/rclcpp/test/rclcpp/test_memory_strategy --gtest_output=xml:/home/jenkins-agent/workspace/nightly_linux-aarch64_repeated/ws/build/rclcpp/test_results/rclcpp/test_memory_strategy.gtest.xml
Running main() from /home/jenkins-agent/workspace/nightly_linux-aarch64_repeated/ws/install/gtest_vendor/src/gtest_vendor/src/gtest_main.cc
[==========] Running 11 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 11 tests from TestMemoryStrategy
[ RUN      ] TestMemoryStrategy.construct_destruct
[       OK ] TestMemoryStrategy.construct_destruct (17 ms)
[ RUN      ] TestMemoryStrategy.get_subscription_by_handle
[ERROR] [1760595178.517516471] [ns.node]: Error in destruction of rcl service handle [~/get_type_description]: rcl node implementation is invalid, at /home/jenkins-agent/workspace/nightly_linux-aarch64_repeated/ws/src/ros2/rcl/rcl/src/rcl/node.c:387
[       OK ] TestMemoryStrategy.get_subscription_by_handle (37 ms)
[ RUN      ] TestMemoryStrategy.get_service_by_handle
-- run_test.py: return code -11
-- run_test.py: generate result file '/home/jenkins-agent/workspace/nightly_linux-aarch64_repeated/ws/build/rclcpp/test_results/rclcpp/test_memory_strategy.gtest.xml' with failed test
-- run_test.py: verify result file '/home/jenkins-agent/workspace/nightly_linux-aarch64_repeated/ws/build/rclcpp/test_results/rclcpp/test_memory_strategy.gtest.xml'
```

### PR DESCRIPTION
**Pull request by fujitatomoya**
## Description

Fixes https://github.com/ros2/rclcpp/issues/2968

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
the memory strategy is holding owning references to the underlying C rcl handles (shared pointer of `rcl_service_t` / `rcl_subscription_t` etc).
those shared_ptrs keep the rcl entities alive past the lifetime of the Node (which un-initializes the rcl_node implementation).
when the rcl service/subscription is finally destroyed, rcl tries to access the node implementation which is already invalid
this generates the error messages during this test.

the objective with those tests are not lifetime of endpoint objects against the node.
these tests basically check if memory strategy APIs work okay with each endpoint.

**Comment by fujitatomoya** [comment]
(i do not think this blocks this PR merge.)

i would like to discuss on the following enhancement as well.

we should not keep the shared pointer to rcl entity handles inside the MemoryStrategy? instead, we could use weak / non-owning references in the following vectors? this avoids extending the lifetime of the underlying rcl entity beyond the node that owns it, while still allowing the memory strategy to observe live handles.

https://github.com/ros2/rclcpp/blob/715a983c9fe31497317bc4545625d13a0142553e/rclcpp/include/rclcpp/strategies/allocator_memory_strategy.hpp#L502-L506

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclcpp#2969
Gist: https://gist.githubusercontent.com/fujitatomoya/97f5d3b73ec7f23155287ca3d7ed8730/raw/da2e3f4ce221c7638d092cc511b37b117fcb6f97/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp
TEST args:  --packages-above rclcpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/17316
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/25462/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/19540/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/4997/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/25762/)

File: rclcpp/test/rclcpp/test_memory_strategy.cpp [hunk 1]
```diff
@@ -228,6 +232,11 @@ TEST_F(TestMemoryStrategy, get_client_by_handle) {
     EXPECT_EQ(
       nullptr,
       memory_strategy()->get_client_by_handle(client_handle, weak_groups_to_nodes));
+    // Clear all handles to cleanup when node is destroyed
+    memory_strategy()->clear_handles();
+    // reset client handle before node destruction, otherwise it tries to access node
+    // via weak_ptr in its deleter
+    client_handle.reset();
```
Comment (skyegalaxy) [inline rclcpp/test/rclcpp/test_memory_strategy.cpp:239]: nit: I was wondering if `memory_strategy()->clear_handles()` could be put in the `TearDown` method to cut down on the test repetition. Would the order of handle clearing and client handle destruction matter for this test?

**Review by skyegalaxy — APPROVED** [review]

File: rclcpp/test/rclcpp/test_memory_strategy.cpp (hunk 1 above)
Comment (fujitatomoya) [reply rclcpp/test/rclcpp/test_memory_strategy.cpp:239]: @skyegalaxy thanks for reviewing this.

the thing is that `memory_strategy()->clear_handles()` needs to be issued before node goes out of the scope. that actually suppress the error message https://github.com/ros2/rclcpp/issues/2968.

Comment (skyegalaxy) [reply rclcpp/test/rclcpp/test_memory_strategy.cpp:239]: Fair enough. LGTM!
