### PR TITLE
fix(Executor): Fixed entities not beeing executed after just beeing added

### LINKED ISSUE #2589: Double spin required since 28.2.0
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 24.04 (Docker)
- Installation type:
  - Binaries
- Version or commit hash:
  - 28.3.1
- DDS implementation:
  - Fast-DDS, Cyclone DDS both
- Client library (if applicable):
  - rclcpp

#### Expected behavior

Spin All, Spin Some work as previously expected

#### Actual behavior

Spinning some or all requires a warmup spin that doesn't do anything before processing useful work. 

#### Additional information

Nav2's CI broke recently with a unit test on a behavior tree node that I got to looking into yesterday. I was chatting with @clalancette about it in [a comment thread](https://github.com/ros-navigation/navigation2/pull/4557#issuecomment-2248839348) and we realized that this is a `rclcpp` regression.

`goal_updater_node` spins an internal executor to process a callback function to get some data that has always worked until recently:  https://github.com/ros-navigation/navigation2/blob/main/nav2_behavior_tree/plugins/decorator/goal_updater_node.cpp#L60. In debugging, I found that it wasn't getting the data the unit test was sending. 

Blaming `Executor::spin_some_impl(std::chrono::nanoseconds max_duration, bool exhaustive)`, I see there's been alot of poking around there recently in the last few months, and a PR to fix some other regression in May, which makes me think maybe there's another regression lurking in that corner.  

## Test A: 

```
  callback_group_executor_.spin_all(std::chrono::milliseconds(200));
```

Pushing the `50`ms up to `200`ms still doesn't work

## Test B:

```
  callback_group_executor_.spin_all(std::chrono::milliseconds(50));
  callback_group_executor_.spin_all(std::chrono::milliseconds(1));
```

**This works**

## Test C:

```
   callback_group_executor_.spin_some(std::chrono::milliseconds(50));
```

Attempting to use spin some instead of spin all also fails 

## Test D:

Lets try ticking the node multiple times while having the single `spin_all(50ms)` (which would cause the spin to be called multiple times)

```
  tree_->rootNode()->executeTick();
  tree_->rootNode()->executeTick();
  tree_->rootNode()->executeTick();
```

**This works**

This experiment proves to me that something is odd with spinning behavior right now requiring multiple calls (whether sequentially or as part of the broader application loop) to process data. The first run is having no effect. I see this running in Nav2's CI that is running Cyclone and I can replicate this locally in a Docker container with Fast-DDS, so I think its a ROS 2 side issue, not DDS.

### PR DESCRIPTION
**Pull request by jmachowinski**
Fixes https://github.com/ros2/rclcpp/issues/2589

### CODE REVIEW

**Review by alsora — APPROVED** [review]

**Comment by alsora** [comment]
CI

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22366/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16629/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1897/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23158/)

File: rclcpp/src/rclcpp/executor.cpp [hunk 1]
```diff
@@ -373,6 +373,12 @@ Executor::spin_some_impl(std::chrono::nanoseconds max_duration, bool exhaustive)
   wait_for_work(std::chrono::milliseconds(0));
   bool just_waited = true;
 
+  if(entities_need_rebuild_) {
```
Comment (wjwwood) [inline rclcpp/src/rclcpp/executor.cpp]: Will probably fail lint? Might just need `ament_uncrustify --reformat .`.

```suggestion
  if (entities_need_rebuild_) {
```

File: rclcpp/src/rclcpp/executor.cpp [hunk 2]
```diff
@@ -409,6 +415,12 @@ Executor::spin_some_impl(std::chrono::nanoseconds max_duration, bool exhaustive)
         // this only happens for spin_all; spin_some only waits at the start
         wait_for_work(std::chrono::milliseconds(0));
         just_waited = true;
+        if(entities_need_rebuild_) {
```
Comment (wjwwood) [inline rclcpp/src/rclcpp/executor.cpp]:
```suggestion
        if (entities_need_rebuild_) {
```

**Review by wjwwood — COMMENTED** [review]
lgtm, but one question

Is it important for `just_waited` to be set to `false` as we are doing, or could we just change the one place it is read to be `if (!entities_need_rebuild_ && just_waited) {`? From a purely semantic point of view, setting `just_waited = false` is kind not "true" because we did actually just wait, we just have another condition to consider now, which is what lead me to wonder why we don't just change the condition logic where we check for whether we just waited or not (line 401).

File: rclcpp/src/rclcpp/executor.cpp (hunk 1 above)
Comment (wjwwood) [reply rclcpp/src/rclcpp/executor.cpp]: Weirdly that doesn't seem to cause the linter to fail... seems fishy.

Comment (fujitatomoya) [reply rclcpp/src/rclcpp/executor.cpp]: i thought that too, this weird thing happens to rcl too? https://github.com/ros2/rcl/pull/1201/files#r1910772257

Comment (jmachowinski) [reply rclcpp/src/rclcpp/executor.cpp]: > Will probably fail lint? Might just need `ament_uncrustify --reformat .`.

I run exactly this command, before every commit....

**Comment by jmachowinski** [comment]
I agree the name just_waited is now odd, I'll try to adopt it a bit...

File: rclcpp/src/rclcpp/executor.cpp (hunk 1 above)
Comment (SteveMacenski) [reply rclcpp/src/rclcpp/executor.cpp]: Note: I've been seeing this in Nav2 recently as well. Here nor there, but the linters seem like they're missing things :upside_down_face:

Comment (clalancette) [reply rclcpp/src/rclcpp/executor.cpp]: In order to move to the new uncrustify for the transition to Ubuntu 24.04, I had to relax the uncrustify rules quite a bit.  So it is possible that uncrustify now allows things that used to be caught.  I'd be on board with tightening those back up, but someone would need to spend the time looking back through the uncrustify configuration, changing those rules, and then fixing whatever fallout there is.

**Comment by SteveMacenski** [comment]
@jmachowinski have you had a chance to work on the review comments? :heart:

**Comment by jmachowinski** [comment]
> @jmachowinski have you had a chance to work on the review comments? ❤️

Friday is my "Ros Day". I would still need a confirmation that this really fixes your bug though...

**Comment by jmachowinski** [comment]
@wjwwood I renamed the just_wait bool to entity_states_fully_polled, so that the semantic should be clearer now.

**Comment by jmachowinski** [comment]
Pulls: ros2/rclcpp#2724
Gist: https://gist.githubusercontent.com/jmachowinski/c67ed34a1751f9eeb89029c25a289a3a/raw/61d3fc5dd6bf750db9a6ffe3b99ecbe7701e7d00/ros2.repos
BUILD args: 
TEST args: 
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15092
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22416/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16673/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1949/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23208/)

**Comment by jmachowinski** [comment]
I would say the windows tests are unrelated, as they are mypy something.
@alsora @ahcorde @fujitatomoya can one of you merge ?

**Comment by fujitatomoya** [comment]
@Mergifyio backport jazzy
