### PR TITLE
Avoid `Resource deadlock avoided` if use intra_process_comms

### LINKED ISSUE #1519: terminate called after throwing an instance of 'std::system_error'   what():  Resource deadlock avoided
## Bug report

**Required Info:**

- Operating System:
  - ubuntu 20.04-->
- Installation type:
  - from source
- Version or commit hash:
  - eloquent
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
I'm writing gtest scripts. My SetUp():
```c++
void SetUp()
{
        auto context = contexts::default_context::get_global_default_context();
        auto options = NodeOptions()
                .context(context)
            // BUG: if set true, test would crash: std::system_error Resource deadlock avoided!
                .use_intra_process_comms(true)
                .automatically_declare_parameters_from_overrides(true);
        mappingNode_ = std::make_shared<Node>("mapping", options);
        bool res = false;
        res = Mapping::getInstance()->initialize(mappingNode_);
        if(!res){
            RCLCPP_ERROR(mappingNode_->get_logger(), "Failed to initialize.");
        }

        executor = std::make_shared<executors::MultiThreadedExecutor>
                   (executor::ExecutorArgs(), 2);
        executor->add_node(mappingNode_);
}
```
In `TEST_F()`, if I used `executor.spin_until_future_complete()` to wait some messages, test program would crash when entering the second TEST_F(). If I use `spin_some()` instead, the program would run without crashing.
You can find the line above `use_intra_process_comms(true)`. If it's set to `true`, 'Resource deadlock avoided' would occur in the second test case. 
```C++
TEST_F()
{
    promise<void> promise;
    Subscription<Mode>::SharedPtr ModeSub;
    auto ModeCB = [&ModeSub, &promise](Mode::SharedPtr msg)->void{
      if(msg->mode == Mode::W &&
         msg->state == Mode::I){
        promise.set_value();
        ModeSub.reset();
      }
    };
    ModeSub =
        pubNode_->create_subscription<Mode>("aa",
                                                   QoS(QoSInitialization::from_rmw(rmw_qos_profile_default)),
                                                   ModeCB);
    shared_future<void> future(promise.get_future());
    ASSERT_EQ(executor->spin_until_future_complete(future, 2s), executor::FutureReturnCode::SUCCESS);
}
```
```
0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6737859 in __GI_abort () at abort.c:79
#2  0x00007ffff6b0c951 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff6b1847c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff6b17459 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6b17e11 in __gxx_personality_v0 () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff6914bdf in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#7  0x00007ffff6915271 in _Unwind_RaiseException () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#8  0x00007ffff6b1878c in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ffff6b0f77f in std::__throw_system_error(int) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007ffff7af3a99 in std::__shared_mutex_pthread::lock (this=0x55555617af50) at /usr/include/c++/9/shared_mutex:188
#11 0x00007ffff7af3b34 in std::shared_timed_mutex::lock (this=0x55555617af50) at /usr/include/c++/9/shared_mutex:459
#12 0x00007ffff7af519b in std::unique_lock<std::shared_timed_mutex>::lock (this=0x7ffffffea490)
    at /usr/include/c++/9/bits/unique_lock.h:141
#13 0x00007ffff7af45dd in std::unique_lock<std::shared_timed_mutex>::unique_lock (this=0x7ffffffea490, __m=...)
    at /usr/include/c++/9/bits/unique_lock.h:71
#14 0x00007ffff7af2d3e in rclcpp::experimental::IntraProcessManager::remove_subscription (this=0x55555617aea0, 
    intra_process_subscription_id=2)
    at /home/chervon/ros2_eloquent_source/src/ros2/rclcpp/rclcpp/src/rclcpp/intra_process_manager.cpp:86
#15 0x00007ffff7bd3b67 in rclcpp::SubscriptionBase::~SubscriptionBase (this=0x55555619ac90, __in_chrg=<optimized out>)
    at /home/chervon/ros2_eloquent_source/src/ros2/rclcpp/rclcpp/src/rclcpp/subscription_base.cpp:96
--Type <RET> for more, q to quit, c to continue without paging--
pp::message_memory_strategy::MessageMemoryStrategy<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void> > >::~Subscription (this=0x55555619ac90, __in_chrg=<optimized out>)
    at /home/chervon/ros2_eloquent_source/src/ros2/rclcpp/rclcpp/include/rclcpp/subscription.hpp:67
#17 0x00007ffff7c02087 in __gnu_cxx::new_allocator<rclcpp::Subscription<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void> > > >::destroy<rclcpp::Subscription<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void> > > > (this=0x55555619ac90, __p=0x55555619ac90)
    at /usr/include/c++/9/ext/new_allocator.h:153
#18 0x00007ffff7c00065 in std::allocator_traits<std::allocator<rclcpp::Subscription<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void> > > > >::destroy<rclcpp::Subscription<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void> > > > (__a=..., __p=0x55555619ac90)
    at /usr/include/c++/9/bits/alloc_traits.h:497

#19 0x00007ffff7bfd13d in std::_Sp_counted_ptr_inplace<rclcpp::Subscription<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void> > >, std::allocator<rclcpp::Subscription<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void> > > >, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x55555619ac80)
    at /usr/include/c++/9/bits/shared_ptr_base.h:557
#20 0x000055555563c380 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x55555619ac80) at /usr/include/c++/9/bits/shared_ptr_base.h:155
#21 0x0000555555637ec3 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7ffffffeb7d8, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:730
#22 0x00007ffff7bd9ad8 in std::__shared_ptr<rclcpp::Subscription<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void> > >, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7ffffffeb7d0, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#23 0x00007ffff7bda7aa in std::__shared_ptr<rclcpp::Subscription<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void> > >, (__gnu_cxx::_Lock_policy)2>::reset (this=0x5555561a2b80) at /usr/include/c++/9/bits/shared_ptr_base.h:1287
#24 0x00007ffff7bd785e in rclcpp::TimeSource::detachNode (this=0x5555561a2ac8) at /home/chervon/ros2_eloquent_source/src/ros2/rclcpp/rclcpp/src/rclcpp/time_source.cpp:132
#25 0x00007ffff7bd7ed0 in rclcpp::TimeSource::~TimeSource (this=0x5555561a2ac8, __in_chrg=<optimized out>) at /home/chervon/ros2_eloquent_source/src/ros2/rclcpp/rclcpp/src/rclcpp/time_source.cpp:180
#26 0x00007ffff7b5ec0e in rclcpp::node_interfaces::NodeTimeSource::~NodeTimeSource (this=0x5555561a2a50, __in_chrg=<optimized out>)
    at /home/chervon/ros2_eloquent_source/src/ros2/rclcpp/rclcpp/src/rclcpp/node_interfaces/node_time_source.cpp:49
#27 0x00007ffff7b5ecaa in rclcpp::node_interfaces::NodeTimeSource::~NodeTimeSource (this=0x5555561a2a50, __in_chrg=<optimized out>)
    at /home/chervon/ros2_eloquent_source/src/ros2/rclcpp/rclcpp/src/rclcpp/node_interfaces/node_time_source.cpp:50
#28 0x00007ffff7b1b780 in std::_Sp_counted_ptr<rclcpp::node_interfaces::NodeTimeSource*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x555556198760) at /usr/include/c++/9/bits/shared_ptr_base.h:377
#29 0x000055555563c380 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x555556198760) at /usr/include/c++/9/bits/shared_ptr_base.h:155
#30 0x0000555555637ec3 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x555555fbb9c0, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:730
#31 0x00007ffff7b1416c in std::__shared_ptr<rclcpp::node_interfaces::NodeTimeSourceInterface, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x555555fbb9b8, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#32 0x00007ffff7b1418c in std::shared_ptr<rclcpp::node_interfaces::NodeTimeSourceInterface>::~shared_ptr (this=0x555555fbb9b8, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr.h:103
#33 0x00007ffff7b11fb0 in rclcpp::Node::~Node (this=0x555555fbb920, __in_chrg=<optimized out>) at /home/chervon/ros2_eloquent_source/src/ros2/rclcpp/rclcpp/src/rclcpp/node.cpp:185
#34 0x000055555568cec5 in __gnu_cxx::new_allocator<rclcpp::Node>::destroy<rclcpp::Node> (this=0x555555fbb920, __p=0x555555fbb920) at /usr/include/c++/9/ext/new_allocator.h:153
#35 0x000055555568b483 in std::allocator_traits<std::allocator<rclcpp::Node> >::destroy<rclcpp::Node> (__a=..., __p=0x555555fbb920) at /usr/include/c++/9/bits/alloc_traits.h:497
#36 0x0000555555687d19 in std::_Sp_counted_ptr_inplace<rclcpp::Node, std::allocator<rclcpp::Node>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x555555fbb910) at /usr/include/c++/9/bits/shared_ptr_base.h:557
#37 0x000055555563c380 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x555555fbb910) at /usr/include/c++/9/bits/shared_ptr_base.h:155
#38 0x0000555555637ec3 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x555555fbef50, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:730
#39 0x00005555556351de in std::__shared_ptr<rclcpp::Node, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x555555fbef48, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#40 0x00005555556351fe in std::shared_ptr<rclcpp::Node>::~shared_ptr (this=0x555555fbef48, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr.h:103
```
#### Expected behavior
Run through each test case.

#### Actual behavior
The first test case passed OK. But test program crashed when entering the second test case.

### PR DESCRIPTION
**Pull request by iuhilnehc-ynos**
Fixes #1519 

NOTE: To reproduce the issue, please refer to https://github.com/ros2/rclcpp/issues/1519#issuecomment-768817649.

Signed-off-by: Chen Lihui <Lihui.Chen@sony.com>

### CODE REVIEW

**Review by ivanpauno — COMMENTED** [review]
Can you explain what is the issue generating the resource deadlock and how does this PR solve the problem?

I have read https://github.com/ros2/rclcpp/issues/1519 and see this patch, and it's not quite clear to me.

**Comment by iuhilnehc-ynos** [comment]
@ivanpauno 

Thank you for letting me explain this issue, and I'll try to explain it more clearly.

1. Generally, a subscription will be destroyed before a node, but we don't expect users to always do that.
This issue happened if the subscription destroyed after the node in some condition, and only if using intra_process_comms with true.

2. [Let a callback of subscription keep a node's life](https://github.com/iuhilnehc-ynos/ros2_issues_test/blob/9f0e0024f33d98a638ff7ef064ddac6015418d36/src/rclcpp_issue_1519/test/test1519.cpp#L53-L57)

```
    // a node to create subscription
    {
      auto fcn = std::bind(&Module::stringCallback, module, std::placeholders::_1);
      stringSub = node->create_subscription<std_msgs::msg::String>(
        "/string", 1, fcn);
    }
```

3. [And make sure there is only the callback of subscription to keep the node's life](https://github.com/iuhilnehc-ynos/ros2_issues_test/blob/9f0e0024f33d98a638ff7ef064ddac6015418d36/src/rclcpp_issue_1519/test/test1519.cpp#L69-L70)

```
    (actually, the following two lines can also use `reset()`, to write the following code is to show the real case if possible)
    node = std::make_shared<rclcpp::Node>("test_bug_new_node", options);
    module = std::make_shared<Module>(node);
```

4. [After that, we reset the old `stringSub`](https://github.com/iuhilnehc-ynos/ros2_issues_test/blob/9f0e0024f33d98a638ff7ef064ddac6015418d36/src/rclcpp_issue_1519/test/test1519.cpp#L72-L73), which will cause calling `std::unique_lock<std::shared_timed_mutex> lock(mutex_)` twice for the same mutex.

```
    (Using `stringSub.reset()` can also reproduce the issue)
    stringSub = node->create_subscription<std_msgs::msg::String>(
      "/string", 1, fcn);
```


<details><summary> Detailed callstack and more explanation </summary>
<p>

Frame `#77` ready to destruct the subscription

Frame `#75` ready to call `std::unique_lock<std::shared_timed_mutex> lock(mutex_);` first time

Frame `#74` after calling `std::unique_lock<std::shared_timed_mutex> lock(mutex_);`, and then to erase subscriptions_ that will destruct `SubscriptionIntraProcess`, which was added by `IntraProcessManager::add_subscription` at [subscription.hpp](https://github.com/ros2/rclcpp/blob/963b5bbea3d1face8d24707f60972e8e0e2b3fff/rclcpp/include/rclcpp/subscription.hpp#L193) before. So `subscription` is only kept in `subscriptions_`(SubscriptionInfo) of IntraProcessManager. (We need to avoid this event happened)

Frame `#66` evil begins, to call the destructor of `SubscriptionInfo`

Frmae `#57`(rclcpp::AnySubscriptionCallback::~AnySubscriptionCallback) -> Frame `#33`(rclcpp::Node::~Node) -> Frame `#16`(rclcpp::Subscription::~Subscription) -> Frame `#15`(rclcpp::SubscriptionBase::~SubscriptionBase) -> Frame `#14`(rclcpp::experimental::IntraProcessManager::remove_subscription) -> call `std::unique_lock<std::shared_timed_mutex> lock(mutex_);` second time


```shell
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided

Thread 1 "test1519" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7297859 in __GI_abort () at abort.c:79
#2  0x00007ffff751f951 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff752b47c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff752a459 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff752ae11 in __gxx_personality_v0 () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7476bdf in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#7  0x00007ffff7477271 in _Unwind_RaiseException () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#8  0x00007ffff752b78c in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ffff752277f in std::__throw_system_error(int) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007ffff7d3e709 in std::__shared_mutex_pthread::lock (this=0x555555897cf0) at /usr/include/c++/9/shared_mutex:188
#11 0x00007ffff7d3e7a4 in std::shared_timed_mutex::lock (this=0x555555897cf0) at /usr/include/c++/9/shared_mutex:459
#12 0x00007ffff7d3fe67 in std::unique_lock<std::shared_timed_mutex>::lock (this=0x7fffffff9510) at /usr/include/c++/9/bits/unique_lock.h:141
#13 0x00007ffff7d3f2a9 in std::unique_lock<std::shared_timed_mutex>::unique_lock (this=0x7fffffff9510, __m=...) at /usr/include/c++/9/bits/unique_lock.h:71
#14 0x00007ffff7d3db14 in rclcpp::experimental::IntraProcessManager::remove_subscription (this=0x555555897c40, intra_process_subscription_id=2)
    at /home/chenlh/Projects/ROS2/ros2-master/src/ros2/rclcpp/rclcpp/src/rclcpp/intra_process_manager.cpp:83
#15 0x00007ffff7e30b71 in rclcpp::SubscriptionBase::~SubscriptionBase (this=0x5555558abbf0, __in_chrg=<optimized out>)
    at /home/chenlh/Projects/ROS2/ros2-master/src/ros2/rclcpp/rclcpp/src/rclcpp/subscription_base.cpp:97
#16 0x00007ffff7e7aa44 in rclcpp::Subscription<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void> > >::~Subscription (this=0x5555558abbf0, 
    __in_chrg=<optimized out>) at /home/chenlh/Projects/ROS2/ros2-master/src/ros2/rclcpp/rclcpp/include/rclcpp/subscription.hpp:69
#17 0x00007ffff7e8898f in __gnu_cxx::new_allocator<rclcpp::Subscription<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void> > > >::destroy<rclcpp::Subscription<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void> > > > (this=0x5555558abbf0, __p=0x5555558abbf0) at /usr/include/c++/9/ext/new_allocator.h:153
#18 0x00007ffff7e85813 in std::allocator_traits<std::allocator<rclcpp::Subscription<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void> > > > >::destroy<rclcpp::Subscription<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void> > > > (__a=..., __p=0x5555558abbf0) at /usr/include/c++/9/bits/alloc_traits.h:497
#19 0x00007ffff7e80e25 in std::_Sp_counted_ptr_inplace<rclcpp::Subscription<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void> > >, std::allocator<rclcpp::Subscription<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void> > > >, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x5555558abbe0)
    at /usr/include/c++/9/bits/shared_ptr_base.h:557
#20 0x0000555555700184 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x5555558abbe0) at /usr/include/c++/9/bits/shared_ptr_base.h:155
#21 0x00005555556fd4c7 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7fffffff9ec8, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr_base.h:730
#22 0x00007ffff7e3a29a in std::__shared_ptr<rclcpp::Subscription<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void> > >, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7fffffff9ec0, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#23 0x00007ffff7e3b6e2 in std::__shared_ptr<rclcpp::Subscription<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<rcl_interfaces::msg::ParameterEvent_<std::allocator<void> >, std::allocator<void> > >, (__gnu_cxx::_Lock_policy)2>::reset (
--Type <RET> for more, q to quit, c to continue without paging--
    this=0x555555874c18) at /usr/include/c++/9/bits/shared_ptr_base.h:1287
#24 0x00007ffff7e36e4a in rclcpp::TimeSource::detachNode (this=0x555555874b08)
    at /home/chenlh/Projects/ROS2/ros2-master/src/ros2/rclcpp/rclcpp/src/rclcpp/time_source.cpp:131
#25 0x00007ffff7e374a4 in rclcpp::TimeSource::~TimeSource (this=0x555555874b08, __in_chrg=<optimized out>)
    at /home/chenlh/Projects/ROS2/ros2-master/src/ros2/rclcpp/rclcpp/src/rclcpp/time_source.cpp:179
#26 0x00007ffff7db1d64 in rclcpp::node_interfaces::NodeTimeSource::~NodeTimeSource (this=0x555555874a90, __in_chrg=<optimized out>)
    at /home/chenlh/Projects/ROS2/ros2-master/src/ros2/rclcpp/rclcpp/src/rclcpp/node_interfaces/node_time_source.cpp:51
#27 0x00007ffff7db1e00 in rclcpp::node_interfaces::NodeTimeSource::~NodeTimeSource (this=0x555555874a90, __in_chrg=<optimized out>)
    at /home/chenlh/Projects/ROS2/ros2-master/src/ros2/rclcpp/rclcpp/src/rclcpp/node_interfaces/node_time_source.cpp:52
#28 0x00007ffff7d647e2 in std::_Sp_counted_ptr<rclcpp::node_interfaces::NodeTimeSource*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x555555897ea0)
    at /usr/include/c++/9/bits/shared_ptr_base.h:377
#29 0x0000555555700184 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x555555897ea0) at /usr/include/c++/9/bits/shared_ptr_base.h:155
#30 0x00005555556fd4c7 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x5555558406a0, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr_base.h:730
#31 0x00007ffff7d5db5c in std::__shared_ptr<rclcpp::node_interfaces::NodeTimeSourceInterface, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x555555840698, 
    __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#32 0x00007ffff7d5db7c in std::shared_ptr<rclcpp::node_interfaces::NodeTimeSourceInterface>::~shared_ptr (this=0x555555840698, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr.h:103
#33 0x00007ffff7d5b688 in rclcpp::Node::~Node (this=0x555555840600, __in_chrg=<optimized out>)
    at /home/chenlh/Projects/ROS2/ros2-master/src/ros2/rclcpp/rclcpp/src/rclcpp/node.cpp:187
#34 0x000055555574c06b in __gnu_cxx::new_allocator<rclcpp::Node>::destroy<rclcpp::Node> (this=0x555555840600, __p=0x555555840600)
    at /usr/include/c++/9/ext/new_allocator.h:153
#35 0x0000555555749503 in std::allocator_traits<std::allocator<rclcpp::Node> >::destroy<rclcpp::Node> (__a=..., __p=0x555555840600)
    at /usr/include/c++/9/bits/alloc_traits.h:497
#36 0x00005555557462b5 in std::_Sp_counted_ptr_inplace<rclcpp::Node, std::allocator<rclcpp::Node>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x5555558405f0)
    at /usr/include/c++/9/bits/shared_ptr_base.h:557
#37 0x0000555555700184 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x5555558405f0) at /usr/include/c++/9/bits/shared_ptr_base.h:155
#38 0x00005555556fd4c7 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x5555558bb428, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr_base.h:730
#39 0x00005555556fcb22 in std::__shared_ptr<rclcpp::Node, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x5555558bb420, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#40 0x00005555556fcb6c in std::shared_ptr<rclcpp::Node>::~shared_ptr (this=0x5555558bb420, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr.h:103
#41 0x000055555574c00a in Module::~Module (this=0x5555558bb420, __in_chrg=<optimized out>)
    at /home/chenlh/Projects/ROS2/ros2_issues_test/src/rclcpp_issue_1519/test/test1519.cpp:31
#42 0x000055555574c02e in __gnu_cxx::new_allocator<Module>::destroy<Module> (this=0x5555558bb420, __p=0x5555558bb420) at /usr/include/c++/9/ext/new_allocator.h:153
#43 0x00005555557494bb in std::allocator_traits<std::allocator<Module> >::destroy<Module> (__a=..., __p=0x5555558bb420) at /usr/include/c++/9/bits/alloc_traits.h:497
#44 0x000055555574610b in std::_Sp_counted_ptr_inplace<Module, std::allocator<Module>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x5555558bb410)
    at /usr/include/c++/9/bits/shared_ptr_base.h:557
#45 0x0000555555700184 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x5555558bb410) at /usr/include/c++/9/bits/shared_ptr_base.h:155
#46 0x00005555556fd4c7 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x5555558be678, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr_base.h:730
#47 0x00005555556fccd0 in std::__shared_ptr<Module, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x5555558be670, __in_chrg=<optimized out>)
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#48 0x00005555556fccf0 in std::shared_ptr<Module>::~shared_ptr (this=0x5555558be670, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr.h:103
#49 0x00005555556fce34 in std::_Head_base<0ul, std::shared_ptr<Module>, false>::~_Head_base (this=0x5555558be670, __in_chrg=<optimized out>)
    at /usr/include/c++/9/tuple:120
#50 0x00005555556fce54 in std::_Tuple_impl<0ul, std::shared_ptr<Module>, std::_Placeholder<1> >::~_Tuple_impl (this=0x5555558be670, __in_chrg=<optimized out>)
    at /usr/include/c++/9/tuple:185
#51 0x00005555556fce74 in std::tuple<std::shared_ptr<Module>, std::_Placeholder<1> >::~tuple (this=0x5555558be670, __in_chrg=<optimized out>)
    at /usr/include/c++/9/tuple:893
#52 0x00005555556fce98 in std::_Bind<void (Module::*(std::shared_ptr<Module>, std::_Placeholder<1>))(std::shared_ptr<std_msgs::msg::String_<std::allocator<void> > >)>::~_Bind() (this=0x5555558be660, __in_chrg=<optimized out>) at /usr/include/c++/9/functional:386
#53 0x0000555555716e42 in std::_Function_base::_Base_manager<std::_Bind<void (Module::*(std::shared_ptr<Module>, std::_Placeholder<1>))(std::shared_ptr<std_msgs::msg::String_<std::allocator<void> > >)> >::_M_destroy(std::_Any_data&, std::integral_constant<bool, false>) (__victim=...) at /usr/include/c++/9/bits/std_function.h:191
#54 0x0000555555714b81 in std::_Function_base::_Base_manager<std::_Bind<void (Module::*(std::shared_ptr<Module>, std::_Placeholder<1>))(std::shared_ptr<std_msgs::msg::String_<std::allocator<void> > >)> >::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation) (__dest=..., __source=..., 
    __op=std::__destroy_functor) at /usr/include/c++/9/bits/std_function.h:215
#55 0x00005555556fa133 in std::_Function_base::~_Function_base (this=0x5555558be540, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/std_function.h:260
#56 0x00005555557074ca in std::function<void (std::shared_ptr<std_msgs::msg::String_<std::allocator<void> > >)>::~function() (this=0x5555558be540, 
    __in_chrg=<optimized out>) at /usr/include/c++/9/bits/std_function.h:369
#57 0x0000555555707632 in rclcpp::AnySubscriptionCallback<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void> >::~AnySubscriptionCallback (
    this=0x5555558be540, __in_chrg=<optimized out>) at /home/chenlh/Projects/ROS2/ros2-master/install/include/rclcpp/any_subscription_callback.hpp:37
#58 0x0000555555744581 in rclcpp::experimental::SubscriptionIntraProcess<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void>, std::default_delete<std_msgs::msg::String_<std::allocator<void> > >, std_msgs::msg::String_<std::allocator<void> > >::~SubscriptionIntraProcess (this=0x5555558be480, 
    __in_chrg=<optimized out>) at /home/chenlh/Projects/ROS2/ros2-master/install/include/rclcpp/experimental/subscription_intra_process.hpp:115
#59 0x000055555574aab3 in __gnu_cxx::new_allocator<rclcpp::experimental::SubscriptionIntraProcess<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void>, std::default_delete<std_msgs::msg::String_<std::allocator<void> > >, std_msgs::msg::String_<std::allocator<void> > > >::destroy<rclcpp::experimental::SubscriptionIntraProcess<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void>, std::default_delete<std_msgs::msg::String_<std::allocator<void> > >, std_msgs::msg::String_<std::allocator<void> > > > (this=0x5555558be480, __p=0x5555558be480) at /usr/include/c++/9/ext/new_allocator.h:153
#60 0x0000555555747e77 in std::allocator_traits<std::allocator<rclcpp::experimental::SubscriptionIntraProcess<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void>, std::default_delete<std_msgs::msg::String_<std::allocator<void> > >, std_msgs::msg::String_<std::allocator<void> > > > >::destroy<rclcpp::experimental::SubscriptionIntraProcess<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void>, std::default_delete<std_msgs::msg::String_<std::allocator<void> > >, std_msgs::msg::String_<std::allocator<void> > > > (__a=..., __p=0x5555558be480) at /usr/include/c++/9/bits/alloc_traits.h:497
#61 0x0000555555741d0b in std::_Sp_counted_ptr_inplace<rclcpp::experimental::SubscriptionIntraProcess<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void>, std::default_delete<std_msgs::msg::String_<std::allocator<void> > >, std_msgs::msg::String_<std::allocator<void> > >, std::allocator<rclcpp::experimental::SubscriptionIntraProcess<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void>, std::default_delete<std_msgs::msg::String_<std::allocator<void> > >, std_msgs::msg::String_<std::allocator<void> > > >, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x5555558be470) at /usr/include/c++/9/bits/shared_ptr_base.h:557
#62 0x0000555555700184 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x5555558be470) at /usr/include/c++/9/bits/shared_ptr_base.h:155
#63 0x00005555556fd4c7 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x5555558ac388, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr_base.h:730
#64 0x00005555557161be in std::__shared_ptr<rclcpp::experimental::SubscriptionIntraProcessBase, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x5555558ac380, 
    __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#65 0x0000555555716208 in std::shared_ptr<rclcpp::experimental::SubscriptionIntraProcessBase>::~shared_ptr (this=0x5555558ac380, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr.h:103
--Type <RET> for more, q to quit, c to continue without paging--
#66 0x00007ffff7d3f04c in rclcpp::experimental::IntraProcessManager::SubscriptionInfo::~SubscriptionInfo (this=0x5555558ac380, __in_chrg=<optimized out>)
    at /home/chenlh/Projects/ROS2/ros2-master/src/ros2/rclcpp/rclcpp/include/rclcpp/experimental/intra_process_manager.hpp:306
#67 0x00007ffff7d451e8 in std::pair<unsigned long const, rclcpp::experimental::IntraProcessManager::SubscriptionInfo>::~pair (this=0x5555558ac378, 
    __in_chrg=<optimized out>) at /usr/include/c++/9/bits/stl_pair.h:208
#68 0x00007ffff7d4520c in __gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<unsigned long const, rclcpp::experimental::IntraProcessManager::SubscriptionInfo>, false> >::destroy<std::pair<unsigned long const, rclcpp::experimental::IntraProcessManager::SubscriptionInfo> > (this=0x555555897c80, __p=0x5555558ac378)
    at /usr/include/c++/9/ext/new_allocator.h:153
#69 0x00007ffff7d44188 in std::allocator_traits<std::allocator<std::__detail::_Hash_node<std::pair<unsigned long const, rclcpp::experimental::IntraProcessManager::SubscriptionInfo>, false> > >::destroy<std::pair<unsigned long const, rclcpp::experimental::IntraProcessManager::SubscriptionInfo> > (__a=..., __p=0x5555558ac378)
    at /usr/include/c++/9/bits/alloc_traits.h:497
#70 0x00007ffff7d42977 in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<unsigned long const, rclcpp::experimental::IntraProcessManager::SubscriptionInfo>, false> > >::_M_deallocate_node (this=0x555555897c80, __n=0x5555558ac370) at /usr/include/c++/9/bits/hashtable_policy.h:2102
#71 0x00007ffff7d43a67 in std::_Hashtable<unsigned long, std::pair<unsigned long const, rclcpp::experimental::IntraProcessManager::SubscriptionInfo>, std::allocator<std::pair<unsigned long const, rclcpp::experimental::IntraProcessManager::SubscriptionInfo> >, std::__detail::_Select1st, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_erase (this=0x555555897c80, __bkt=3, __prev_n=0x5555558e4f80, __n=0x5555558ac370) at /usr/include/c++/9/bits/hashtable.h:1886
#72 0x00007ffff7d420d1 in std::_Hashtable<unsigned long, std::pair<unsigned long const, rclcpp::experimental::IntraProcessManager::SubscriptionInfo>, std::allocator<std::pair<unsigned long const, rclcpp::experimental::IntraProcessManager::SubscriptionInfo> >, std::__detail::_Select1st, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_erase (this=0x555555897c80, __k=@0x7fffffffae70: 3) at /usr/include/c++/9/bits/hashtable.h:1912
#73 0x00007ffff7d4054c in std::_Hashtable<unsigned long, std::pair<unsigned long const, rclcpp::experimental::IntraProcessManager::SubscriptionInfo>, std::allocator<std::pair<unsigned long const, rclcpp::experimental::IntraProcessManager::SubscriptionInfo> >, std::__detail::_Select1st, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::erase (this=0x555555897c80, __k=@0x7fffffffae70: 3) at /usr/include/c++/9/bits/hashtable.h:772
#74 0x00007ffff7d3f5c7 in std::unordered_map<unsigned long, rclcpp::experimental::IntraProcessManager::SubscriptionInfo, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, rclcpp::experimental::IntraProcessManager::SubscriptionInfo> > >::erase (this=0x555555897c80, 
    __x=@0x7fffffffae70: 3) at /usr/include/c++/9/bits/unordered_map.h:815
#75 0x00007ffff7d3db2b in rclcpp::experimental::IntraProcessManager::remove_subscription (this=0x555555897c40, intra_process_subscription_id=3)
    at /home/chenlh/Projects/ROS2/ros2-master/src/ros2/rclcpp/rclcpp/src/rclcpp/intra_process_manager.cpp:85
#76 0x00007ffff7e30b71 in rclcpp::SubscriptionBase::~SubscriptionBase (this=0x5555558ad990, __in_chrg=<optimized out>)
    at /home/chenlh/Projects/ROS2/ros2-master/src/ros2/rclcpp/rclcpp/src/rclcpp/subscription_base.cpp:97
#77 0x000055555573f80e in rclcpp::Subscription<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void> > >::~Subscription (this=0x5555558ad990, __in_chrg=<optimized out>)
    at /home/chenlh/Projects/ROS2/ros2-master/install/include/rclcpp/subscription.hpp:69
#78 0x000055555574be51 in __gnu_cxx::new_allocator<rclcpp::Subscription<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void> > > >::destroy<rclcpp::Subscription<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void> > > >
    (this=0x5555558ad990, __p=0x5555558ad990) at /usr/include/c++/9/ext/new_allocator.h:153
#79 0x000055555574927b in std::allocator_traits<std::allocator<rclcpp::Subscription<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void> > > > >::destroy<rclcpp::Subscription<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void> > > > (__a=..., __p=0x5555558ad990) at /usr/include/c++/9/bits/alloc_traits.h:497
--Type <RET> for more, q to quit, c to continue without paging--
#80 0x00005555557453bb in std::_Sp_counted_ptr_inplace<rclcpp::Subscription<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void> > >, std::allocator<rclcpp::Subscription<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void> > > >, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x5555558ad980) at /usr/include/c++/9/bits/shared_ptr_base.h:557
#81 0x0000555555700184 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x5555558ad980) at /usr/include/c++/9/bits/shared_ptr_base.h:155
#82 0x00005555556fd4c7 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7fffffffb878, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr_base.h:730
#83 0x00005555556fcd14 in std::__shared_ptr<rclcpp::Subscription<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void> > >, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7fffffffb870, 
    __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#84 0x0000555555702494 in std::__shared_ptr<rclcpp::Subscription<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void> > >, (__gnu_cxx::_Lock_policy)2>::operator= (this=0x7fffffffb900, __r=...)
    at /usr/include/c++/9/bits/shared_ptr_base.h:1265
#85 0x00005555556ffe3a in std::shared_ptr<rclcpp::Subscription<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void>, rclcpp::message_memory_strategy::MessageMemoryStrategy<std_msgs::msg::String_<std::allocator<void> >, std::allocator<void> > > >::operator= (this=0x7fffffffb900, __r=...)
    at /usr/include/c++/9/bits/shared_ptr.h:335
#86 0x00005555556f9281 in TestBug1519_test_resource_deadlock_Test::<lambda()>::operator()(void) const (__closure=0x7fffffffbfd7)
    at /home/chenlh/Projects/ROS2/ros2_issues_test/src/rclcpp_issue_1519/test/test1519.cpp:73
#87 0x00005555556f9581 in TestBug1519_test_resource_deadlock_Test::TestBody (this=0x55555583bbd0)
    at /home/chenlh/Projects/ROS2/ros2_issues_test/src/rclcpp_issue_1519/test/test1519.cpp:78
#88 0x000055555578a34e in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (object=0x55555583bbd0, 
    method=&virtual testing::Test::TestBody(), location=0x5555557a34b3 "the test body")
    at /home/chenlh/Projects/ROS2/ros2-master/install/src/gtest_vendor/./src/gtest.cc:2433
#89 0x0000555555782fef in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x55555583bbd0, 
    method=&virtual testing::Test::TestBody(), location=0x5555557a34b3 "the test body")
    at /home/chenlh/Projects/ROS2/ros2-master/install/src/gtest_vendor/./src/gtest.cc:2469
#90 0x000055555575df3a in testing::Test::Run (this=0x55555583bbd0) at /home/chenlh/Projects/ROS2/ros2-master/install/src/gtest_vendor/./src/gtest.cc:2508
#91 0x000055555575e933 in testing::TestInfo::Run (this=0x55555583b050) at /home/chenlh/Projects/ROS2/ros2-master/install/src/gtest_vendor/./src/gtest.cc:2684
#92 0x000055555575f078 in testing::TestSuite::Run (this=0x55555583b1d0) at /home/chenlh/Projects/ROS2/ros2-master/install/src/gtest_vendor/./src/gtest.cc:2816
#93 0x000055555576b15e in testing::internal::UnitTestImpl::RunAllTests (this=0x5555557ffbd0)
    at /home/chenlh/Projects/ROS2/ros2-master/install/src/gtest_vendor/./src/gtest.cc:5338
#94 0x000055555578b87c in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x5555557ffbd0, 
    method=(bool (testing::internal::UnitTestImpl::*)(class testing::internal::UnitTestImpl * const)) 0x55555576ad56 <testing::internal::UnitTestImpl::RunAllTests()>, location=0x5555557a3ef0 "auxiliary test code (environments or event listeners)")
    at /home/chenlh/Projects/ROS2/ros2-master/install/src/gtest_vendor/./src/gtest.cc:2433
#95 0x000055555578422d in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x5555557ffbd0, 
    method=(bool (testing::internal::UnitTestImpl::*)(class testing::internal::UnitTestImpl * const)) 0x55555576ad56 <testing::internal::UnitTestImpl::RunAllTests()>, location=0x5555557a3ef0 "auxiliary test code (environments or event listeners)")
    at /home/chenlh/Projects/ROS2/ros2-master/install/src/gtest_vendor/./src/gtest.cc:2469
#96 0x000055555576997a in testing::UnitTest::Run (this=0x5555557fe720 <testing::UnitTest::GetInstance()::instance>)
    at /home/chenlh/Projects/ROS2/ros2-master/install/src/gtest_vendor/./src/gtest.cc:4925
#97 0x00005555557559ba in RUN_ALL_TESTS () at /home/chenlh/Projects/ROS2/ros2-master/install/src/gtest_vendor/include/gtest/gtest.h:2473
--Type <RET> for more, q to quit, c to continue without paging--
#98 0x000055555575593c in main (argc=1, argv=0x7fffffffc508) at /home/chenlh/Projects/ROS2/ros2-master/install/src/gtest_vendor/src/gtest_main.cc:45

```

</p>
</details>


This PR is trying to avoid destructing `SubscriptionIntraProcess` while erasing subscriptions_ at Frame `#74`, do you have any suggestion to fix this issue?

File: rclcpp/include/rclcpp/experimental/intra_process_manager.hpp [hunk 1]
```diff
@@ -361,13 +361,16 @@ class IntraProcessManager
       if (subscription_it == subscriptions_.end()) {
         throw std::runtime_error("subscription has unexpectedly gone out of scope");
       }
-      auto subscription_base = subscription_it->second.subscription;
+      auto subscription_base_weak = subscription_it->second.subscription;
+      if (auto subscription_base = subscription_base_weak.lock()) {
```
Comment (ivanpauno) [inline rclcpp/include/rclcpp/experimental/intra_process_manager.hpp:365]:
```suggestion
      auto subscription_base = subscription_it->second.subscription.lock();
      if (subscription_base) {
```

sounds a bit more clear.

File: rclcpp/include/rclcpp/experimental/intra_process_manager.hpp [hunk 2]
```diff
@@ -389,24 +392,27 @@ class IntraProcessManager
...
-
-      auto subscription = std::static_pointer_cast<
-        rclcpp::experimental::SubscriptionIntraProcess<MessageT>
-        >(subscription_base);
-
-      if (std::next(it) == subscription_ids.end()) {
-        // If this is the last subscription, give up ownership
-        subscription->provide_intra_process_message(std::move(message));
+      auto subscription_base_weak = subscription_it->second.subscription;
+      if (auto subscription_base = subscription_base_weak.lock()) {
```
Comment (ivanpauno) [inline rclcpp/include/rclcpp/experimental/intra_process_manager.hpp:396]:
```suggestion
      auto subscription_base = subscription_it->second.subscription.lock();
      if (subscription_base) {
```

File: rclcpp/src/rclcpp/intra_process_manager.cpp [hunk 3]
```diff
@@ -157,7 +157,13 @@ IntraProcessManager::get_subscription_intra_process(uint64_t intra_process_subsc
   if (subscription_it == subscriptions_.end()) {
     return nullptr;
   } else {
-    return subscription_it->second.subscription;
+    auto subscription_weak = subscription_it->second.subscription;
+    if (auto subscription = subscription_weak.lock()) {
```
Comment (ivanpauno) [inline rclcpp/src/rclcpp/intra_process_manager.cpp:161]:
```suggestion
    auto subscription = subscription_it->second.subscription.lock();
    if (subscription) {
```

**Review by ivanpauno — APPROVED** [review]
Looks good to me!!

I think how now `subscription` retains `subscription_intra_process` ownership makes more sense that before.

**Comment by iuhilnehc-ynos** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13558/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8452/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11281/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13623/)

**Comment by iuhilnehc-ynos** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13559/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8453/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11282/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13624/)
*

**Comment by iuhilnehc-ynos** [comment]
CI:

* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11283/)

**Comment by clalancette** [comment]
@iuhilnehc-ynos I think this one is ready for merge, at your convenience.
