### PR TITLE
Harden rclcpp_action::convert().

### LINKED ISSUE #2783: rclcpp_action::convert Function Lacks nullptr Check, Leading to Undefined Behavior
### Operating System:

Linux shangzh-VMware-Virtual-Platform 6.11.0-19-generic #19~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Feb 17 11:51:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### ROS version or commit hash:

 ros2 jazzy

### RMW implementation (if applicable):

_No response_

### RMW Configuration (if applicable):

_No response_

### Client library (if applicable):

rclcpp

### 'ros2 doctor --report' output

```Formatted

```

## Description
In the implementation of the convert function in rclcpp_action, the parameter info is a pointer (rcl_action_goal_info_t *), but the function does not check whether it is nullptr before dereferencing info->goal_id.uuid[i]. This may lead to a segmentation fault (SEGV) when nullptr is passed as an argument, causing the program to crash.

This issue affects scenarios where convert is called with an uninitialized or incorrectly assigned rcl_action_goal_info_t pointer, such as in unit tests or user code.

## Write the following test case:
```cpp
#include <gtest/gtest.h>
#include <limits>
#include <random>
#include "rclcpp_action/types.hpp"

TEST(TestActionTypes, convert_goal_uuid_to_goal_info_null_check) {
  rclcpp_action::GoalUUID goal_id;
  rcl_action_goal_info_t *goal_info = nullptr;
  ASSERT_THROW(rclcpp_action::convert(goal_id, goal_info), std::invalid_argument);
}
```

## Code Analysis
The convert function is defined as follows in rclcpp_action/types.cpp:
```cpp
void convert(const GoalUUID & goal_id, rcl_action_goal_info_t * info)
{
  for (size_t i = 0; i < UUID_SIZE; ++i) {
    info->goal_id.uuid[i] = goal_id[i];  // ⚠️ No nullptr check before dereferencing
  }
}
```
Since info could be nullptr, directly dereferencing info->goal_id.uuid[i] results in undefined behavior (UB), leading to a crash.

### Expected behavior

The convert function should check if info is nullptr at the beginning and throw std::invalid_argument to prevent a crash.

The header file rclcpp_action/types.hpp should include a note explicitly stating that info must not be nullptr.

### Actual behavior

```markdown
Running main() from /home/shangzh/ros2_jazzy/install/gtest_vendor/src/gtest_vendor/src/gtest_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from TestActionTypes
[ RUN      ] TestActionTypes.convert_goal_uuid_to_goal_info_null_check
AddressSanitizer:DEADLYSIGNAL
=================================================================
==61721==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x70ca85dd1246 bp 0x7ffff4af6b70 sp 0x7ffff4af6b50 T0)
==61721==The signal is caused by a WRITE memory access.
==61721==Hint: address points to the zero page.
    #0 0x70ca85dd1246 in rclcpp_action::convert(std::array<unsigned char, 16ul> const&, action_msgs__msg__GoalInfo*) (/home/shangzh/ros2_jazzy/install/rclcpp_action/lib/librclcpp_action.so+0xff246) (BuildId: d6cee34a31953b1f30183ecd33e50175902b4a7d)
    #1 0x5ad6240892f2 in TestActionTypes_convert_goal_uuid_to_goal_info_null_check_Test::TestBody() (/home/shangzh/ros2_jazzy/build/rclcpp_action/test_types+0x882f2) (BuildId: ea826b159a224832324ce06445f61e8056189e43)
    #2 0x5ad6241289b1 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/shangzh/ros2_jazzy/build/rclcpp_action/test_types+0x1279b1) (BuildId: ea826b159a224832324ce06445f61e8056189e43)
    #3 0x5ad624115abd in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/shangzh/ros2_jazzy/build/rclcpp_action/test_types+0x114abd) (BuildId: ea826b159a224832324ce06445f61e8056189e43)
    #4 0x5ad6240bb1bb in testing::Test::Run() (/home/shangzh/ros2_jazzy/build/rclcpp_action/test_types+0xba1bb) (BuildId: ea826b159a224832324ce06445f61e8056189e43)
    #5 0x5ad6240bc997 in testing::TestInfo::Run() (/home/shangzh/ros2_jazzy/build/rclcpp_action/test_types+0xbb997) (BuildId: ea826b159a224832324ce06445f61e8056189e43)
    #6 0x5ad6240bdcf0 in testing::TestSuite::Run() (/home/shangzh/ros2_jazzy/build/rclcpp_action/test_types+0xbccf0) (BuildId: ea826b159a224832324ce06445f61e8056189e43)
    #7 0x5ad6240e4a1b in testing::internal::UnitTestImpl::RunAllTests() (/home/shangzh/ros2_jazzy/build/rclcpp_action/test_types+0xe3a1b) (BuildId: ea826b159a224832324ce06445f61e8056189e43)
    #8 0x5ad62412be0c in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/shangzh/ros2_jazzy/build/rclcpp_action/test_types+0x12ae0c) (BuildId: ea826b159a224832324ce06445f61e8056189e43)
    #9 0x5ad624118d5a in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/shangzh/ros2_jazzy/build/rclcpp_action/test_types+0x117d5a) (BuildId: ea826b159a224832324ce06445f61e8056189e43)
    #10 0x5ad6240e1025 in testing::UnitTest::Run() (/home/shangzh/ros2_jazzy/build/rclcpp_action/test_types+0xe0025) (BuildId: ea826b159a224832324ce06445f61e8056189e43)
    #11 0x5ad62408b4c7 in RUN_ALL_TESTS() (/home/shangzh/ros2_jazzy/build/rclcpp_action/test_types+0x8a4c7) (BuildId: ea826b159a224832324ce06445f61e8056189e43)
    #12 0x5ad62408b413 in main (/home/shangzh/ros2_jazzy/build/rclcpp_action/test_types+0x8a413) (BuildId: ea826b159a224832324ce06445f61e8056189e43)
    #13 0x70ca8382a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #14 0x70ca8382a28a in __libc_start_main_impl ../csu/libc-start.c:360
    #15 0x5ad624089094 in _start (/home/shangzh/ros2_jazzy/build/rclcpp_action/test_types+0x88094) (BuildId: ea826b159a224832324ce06445f61e8056189e43)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/shangzh/ros2_jazzy/install/rclcpp_action/lib/librclcpp_action.so+0xff246) (BuildId: d6cee34a31953b1f30183ecd33e50175902b4a7d) in rclcpp_action::convert(std::array<unsigned char, 16ul> const&, action_msgs__msg__GoalInfo*)
==61721==ABORTING
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by fujitatomoya**
closes https://github.com/ros2/rclcpp/issues/2783

> [!NOTE]
> backport requested to humble and jazzy

### CODE REVIEW

**Comment by fujitatomoya** [comment]
@mjcarroll can you take a look? just adding the null check and test as minor fix.

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclcpp#2786
Gist: https://gist.githubusercontent.com/fujitatomoya/d441c5323b43296cf12ba9408fecc060/raw/9ac8365b8a5f1542582babe345da25e3c56349e3/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp_action
TEST args:  --packages-above rclcpp_action
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15521
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22947/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/17168/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/2433/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23822/)

**Review by fujitatomoya — COMMENTED** [review]
i am not sure why they did not use the reference instead of pointer, but i do not want to change ABI for this fix.

File: rclcpp_action/src/types.cpp [hunk 1]
```diff
@@ -41,6 +41,9 @@ to_string(const GoalUUID & goal_id)
 void
 convert(const GoalUUID & goal_id, rcl_action_goal_info_t * info)
```
Comment (christophebedard) [inline rclcpp_action/src/types.cpp:42]: The function documentation should be updated to mention that it throws `std::invalid_argument` if `info` is `nullptr`. Same below.

**Comment by christophebedard** [comment]
> backport requested to humble and jazzy

Stupid question: is backporting a change that makes a function throw acceptable? I guess in this case it's OK given that it's either this or a SEGV.

**Comment by jmachowinski** [comment]
> > backport requested to humble and jazzy
> 
> Stupid question: is backporting a change that makes a function throw acceptable? I guess in this case it's OK given that it's either this or a SEGV.

I would say yes, as it was not marked nothrow

**Review by jmachowinski — APPROVED** [review]

**Comment by fujitatomoya** [comment]
@jmachowinski @christophebedard thanks for the review, i will patch it with more documentation. and yes i think so, throwing exception is much better and segmentation fault.

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclcpp#2786
Gist: https://gist.githubusercontent.com/fujitatomoya/2451551c82078a7876e4c73ecaeec919/raw/9ac8365b8a5f1542582babe345da25e3c56349e3/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp_action
TEST args:  --packages-above rclcpp_action
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15524
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22950/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/17171/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/2436/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23825/)

**Review by christophebedard — APPROVED** [review]

**Comment by fujitatomoya** [comment]
@Mergifyio backport humble jazzy
