### PR TITLE
[NodeParameters] Set name in param info pre-check

### LINKED ISSUE #1906: broken InvalidParameterValueException message
## Bug report

When setting a parameter in the command line, which is outside of the limits, I get an error message that is not correctly formatted:
```
terminate called after throwing an instance of 'rclcpp::exceptions::InvalidParameterValueException'
  what():  parameter 'ExposureTime' could not be set: Parameter {} doesn't comply with integer range.
```

I assume that `{}` is supposed to be something else, e.g. contain the value.

**Required Info:**

- Operating System: Ubuntu 20.04
- Installation type: binary
- Version or commit hash: galactic
- Client library (if applicable): rclcpp

#### Steps to reproduce issue
1. declare a parameter with bounds: `declare_parameter("ExposureTime", default_value, param_descr);` where `param_descr` is a `ParameterDescriptor` with integer bounds, e.g. (400 ... 20000).
2. initialise the parameter outside of the bounds, e.g. `--ros-args -p ExposureTime:=300`

#### Expected behavior
The exception should contain a useful error message.

#### Actual behavior
`Parameter {} doesn't comply with integer range.` does not make sense to me.

### PR DESCRIPTION
**Pull request by aprotyas**
In `__check_parameters`, there are function-scoped parameter
descriptor structures generated by searching the `ParameterInfo`
map provided from other declaratory functions. This PR populates
this temporary structure with the parameter name information.
This way, the change does not show in other data structures, but the
name field is also not empty when used to generate error messages in
`__check_parameter_value_in_range`.

See this [demo node](https://github.com/aprotyas/ros2_playground/tree/master/rclcpp_1906) for testing purposes.

Fixes #1906.

Signed-off-by: Abrar Rahman Protyasha <aprotyas@u.rochester.edu>

### CODE REVIEW

**Comment by aprotyas** [comment]
I'm unsure how benign this change is given it triggers a couple of parameter test failures in my local setup, but I'd like to get input from maintainers about said failures.

File: rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp [hunk 1]
```diff
@@ -298,6 +298,11 @@ __set_parameters_atomically_common(
   const OnParametersSetCallbackType & callback,
   bool allow_undeclared = false)
 {
+  // Set the parameter name before checks, for more desciprtive error messages
+  for (size_t i = 0; i < parameters.size(); ++i) {
+    const std::string & name = parameters[i].get_name();
+    parameter_infos[name].descriptor.name = parameters[i].get_name();
```
Comment (fujitatomoya) [inline rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp:304]: see https://github.com/ros2/rclcpp/issues/1906#issuecomment-1081089117. i am not sure which tests are actually failing though.

Comment (aprotyas) [reply rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp:304]: Thanks for context about the ParameterInfo structure - do you have a guess why this would cause tests to fail though?

Comment (aprotyas) [reply rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp]: Dropping this approach and favoring 746d93b instead.

Comment (fujitatomoya) [reply rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp]: > Thanks for context about the ParameterInfo structure - do you have a guess why this would cause tests to fail though?

no, not really. i have never tried this patch with my local environment yet.

File: rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp [hunk 2]
```diff
@@ -236,6 +236,7 @@ __check_parameters(
     } else {
       descriptor = parameter_infos[name].descriptor;
     }
+    descriptor.name = name;
```
Comment (fujitatomoya) [inline rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp:239]: this will change the behavior to overwrite the `descriptor.name` from user application.

before, can be `what():  parameter 'foo' could not be set: Parameter {bar} doesn't comply with integer range.`, if user put the descriptor name into `bar`. but after this PR, it will be `what():  parameter 'foo' could not be set: Parameter {foo} doesn't comply with integer range.`. so it cannot print the descriptor name.

probably we would want to store actual parameter name in here if `descriptor.name` is empty? or maybe overwriting would be okay? i would like to hear from other people on this.

Comment (aprotyas) [reply rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp:239]: Good point! I forgot that this descriptor is provided by the user.

> or maybe overwriting would be okay?

Maybe. It's unclear to me what the expectation with the parameter descriptors are. Do they need to be fully populated by the user? What if the user provides a different parameter name? I don't see any code that checks if there is a discrepancy between the parameter name and the name provided in the descriptor, for example.

Comment (aprotyas) [reply rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp:239]: In `declare_parameter(const std::string&)`, it looks like an empty descriptor is provided to satisfy the more complete `declare_parameter` signature. https://github.com/ros2/rclcpp/blob/eac006317692b7eff3aed671eadbff3d72cca098/rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp#L467-L473

That leads me to believe that the `name` argument provided to `declare_parameter` should be the only source of ground truth in this situation, i.e. the `name` argument is the parameter argument, and what is found in the parameter descriptor's name field is irrelevant. I don't have enough context about descriptors to assert this though. Thoughts?

Comment (fujitatomoya) [reply rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp:239]: i might be wrong...

> Do they need to be fully populated by the user?

AFAIK, i do not think so, this is optional and user can/may put some parts only.

> What if the user provides a different parameter name?

in this case, actual parameter name will be used instead of descriptor name. the same behavior goes to type.

i think that this behavior is intentional, so that user application can use descriptor (for instance of range declaration) on some other parameters as well.

> probably we would want to store actual parameter name in here if descriptor.name is empty?

i am currently inclined to have this one.

- we can keep the user descriptor name if that exists.
- we do not change current behavior.
- we can address the original issue https://github.com/ros2/rclcpp/issues/1906

i am open to hear from other opinion 👂

**Review by fujitatomoya — APPROVED** [review]

**Comment by fujitatomoya** [comment]
I am not sure why windows CI is failing, retry.

* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16823/)

**Comment by aprotyas** [comment]
Trying one more time before looking further:
- Windows [Build Status](http://ci.ros2.org/job/ci_windows/16826/)

**Comment by fujitatomoya** [comment]
I believe https://ci.ros2.org/job/ci_windows/16826/cmake/new/NORMAL/ is unrelated to the fix.
