### PR TITLE
Fix topic statistics for IPC subscriptions

### LINKED ISSUE #2911: use_intra_process_comms bypasses topic statistics computation
### Generated by Generative AI

_No response_

### Operating System:

```Ubuntu 22```

### ROS version or commit hash:

humble

### RMW implementation (if applicable):

cyclone

### RMW Configuration (if applicable):

_No response_

### Client library (if applicable):

rclcpp

### 'ros2 doctor --report' output

_No response_

### Steps to reproduce issue

1. Create a publisher of any kind and load its node into a component container
2. Create a rclcpp subscriber to that msg, enable the ```rclcpp::TopicStatisticsOptions```, and use a ConstSharedPtr for the msg-type
3. Enable ```use_intra_process_comms``` when loading this node into the same component container
4. Run this publisher-subscriber-setup and review the topic statistics published on ```/statistics```

### Expected behavior

The topic statistics should be filled with valid values for both, ```message_age``` and ```message period```.

Since the topic_statistics are configured on the subscriber's end only, and technically only need a valid stamped header to be calculated, I expected the topic statistics to work for intra-process communication, as well.

### Actual behavior

When setting ```use_intra_process_comms``` to ```True```, the topic statistics show only ```.nan``` for both, message_age and message period.

When setting ```use_intra_process_comms``` to ```False```, the topic statistics are filled with valid values for both, message_age and message period.

### Additional information

I want to use the topic statistics as a measure of network health in my ros2 system. Naturally, I want to load large msg types, such as point clouds, into composable nodes, but with the topic statistics not working for intra-process communications, I loose my introspection for these crucial topics.

Before, I was using the topic statistics' ```.nan``` values to raise an error because I could be sure that nothing was published. However, with the behavior described above, the topics in the composable nodes will also all show ```.nan```, even though the subscriber's callbacks were executed correctly.

### PR DESCRIPTION
**Pull request by jayyoung**
Continuing on from the discussion here on the original fix: https://github.com/ros2/rclcpp/pull/2913#issuecomment-4223722053 which addresses https://github.com/ros2/rclcpp/issues/2911 we are opening this PR at @fujitatomoya request.

## Description
The root issue: We discovered that when `use_intra_process_comms` is enabled, messages are delivered via `SubscriptionIntraProcess::execute_impl()` which _previously_ never called the topic statistics handler. This causes all statistics to report `NaN` values, making it impossible for us distinguish a healthy IPC subscription from an unhealthy one.

This fix: Here we add a type-erased `StatsHandlerFn` function to `SubscriptionIntraProcess` and connect it up from  the `Subscription` via a lambda. Using the lambda rather than a pointer to `SubscriptionTopicStatistics`  avoids a circular include chain we discovered that could occur if `subscription_topic_statistics.hpp` was included directly from `subscription_intra_process.hpp`.

In the code, we set `source_timestamp`  to the _receive time_ so that `message_age` reports `0ms` rather than an un-initialised value. Our reasoning is that: IPC delivery has no or little transport latency, so near-zero age is OK and expected. As discussed in the original fix PR, there is a one-time warning  emit to inform users that `message_age` is not meaningful for IPC subscriptions.

IN summary this PR  is a revised implementation of the original PR #2913 by @roman-y-wu, with the following differences:

- Uses `std::function` type erasure to avoid the circular include issue we found
- Sets `source_timestamp` to prevent message_age reporting an invalid large value (uninitialised timestamp)

From the original PR, we kept the one-time `RCLCPP_WARN_ONCE` log message to ensures users are not silently surprised by `message_age` reading ~0ms when using IPC subscriptions.

Fixes #2911

### Is this user-facing behavior change?
Yeah it is for us, and addresses an issue we find in production. With this fix topic statistics now report valid values for subscriptions using IPC. Previously all statistics were NaN when IPC was enabled, and this behaviour bit us.

### Did you use Generative AI?
Not on our side. This PR is a small adaptation of a older fix that already existed: https://github.com/ros2/rclcpp/pull/2913

### Additional Information
This fix was first validated as a backport onto ROS 2 Kilted (`rclcpp` == `29.5.6`) and has been running in production at Dexory across a fleet of 126 autonomous warehouse robots for over one month with no issues. Our robots use IPC-enabled lidar pipelines and rely on topic stats to monitor sensor health. `message_period` statistics are now correct and our monitoring correctly detects legitimate sensor failures with this fix.

### CODE REVIEW

File: rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp [hunk 1]
```diff
@@ -197,6 +203,19 @@ class SubscriptionIntraProcess
     msg_info.publisher_gid = {0, {0}};
     msg_info.from_intra_process = true;
 
+    std::chrono::time_point<std::chrono::system_clock> now;
```
Comment (tonynajjar) [inline rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp]: I propose to declare `now` in the scope of the `if` below since it's only used there. Secondly I propose to declare `nanos` outside so that you can reuse it later without casting, since `now` doesn't change

File: rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp
Comment (tonynajjar) [inline rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp:26]: `#include <chrono>` ?

**Comment by tonynajjar** [comment]
Could you also add a test that verifies that with IPC enabled the stats handler fires and reports a non-nan age?

**Comment by tonynajjar** [comment]
@fujitatomoya we'd love to get this merged in before the freeze of rclcpp, I believe on the 20th April. Anything else you would like modified?

File: rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp
Comment (fujitatomoya) [reply rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp:26]: @tonynajjar what is this supposed to mean? 🤔

File: rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp (hunk 1 above)
Comment (jayyoung) [reply rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp]: Good shout, I can simplify even further actually! In https://github.com/ros2/rclcpp/pull/3130/commits/f12988aadad889f20738410f461b0456f11b3a19 `now` is gone and `nanos` is now declared once outside both if blocks and reused, which avoids the duplicate cast. Note that `now` was actually referenced in both `if (stats_handler_) `blocks so I couldn't make it be scoped exclusively inside the first one, but collapsing it into `nanos` directly achieves the same thing I think? let me know what you think!

File: rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp
Comment (jayyoung) [reply rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp:26]: Got it, I take these things for granted :laughing:  added `#include <chrono>` https://github.com/ros2/rclcpp/pull/3130/commits/e87ed41ce7296c8d7f4ed98adc50cf90d162121b

**Comment by jayyoung** [comment]
> Could you also add a test that verifies that with IPC enabled the stats handler fires and reports a non-nan age?

Added a little one https://github.com/ros2/rclcpp/pull/3130/commits/cdf6632da4c66a34916b0b2a8b8464756d95c161

**Review by tonynajjar — APPROVED** [review]

**Review by fujitatomoya — APPROVED** [review]
lgtm, test would be ideal.

File: rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp
Comment (tonynajjar) [reply rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp:26]: @fujitatomoya I meant to include chrono but text in between <  > in mardown disappears 😄

**Comment by tonynajjar** [comment]
@fujitatomoya a test was added, anything else to test?

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclcpp#3130
Gist: https://gist.githubusercontent.com/fujitatomoya/72662fc102cdd964a64583c3201db0d6/raw/d39d13ab88b54886116348d2fb6418264a592531/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp
TEST args:  --packages-above rclcpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/18997
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/28761/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/21580/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/8603/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/27628/)

**Comment by jayyoung** [comment]
just added https://github.com/ros2/rclcpp/pull/3130/commits/175ce2fe4604fca591587c4bb59b9418da7a0349 which fixes the linting failure @fujitatomoya, thanks! can you re-trigger CI please?

**Comment by tonynajjar** [comment]
@jmachowinski I'm asking you since you are roughly in our timezone, could you please relaunch CI so we can try to get this in before the freeze? Thanks!

**Comment by jmachowinski** [comment]
Pulls: ros2/rclcpp#3130
Gist: https://gist.githubusercontent.com/jmachowinski/a744ece36c05d299e61f7521a2fcb409/raw/d39d13ab88b54886116348d2fb6418264a592531/ros2.repos
BUILD args: 
TEST args: 
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/19012
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/28777/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/21595/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/8618/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/27645/)

**Comment by jmachowinski** [comment]
@tonynajjar I don't remember Munich to be in a different time zone than Bremen ;-P

**Comment by tonynajjar** [comment]
I was including my colleague in the UK in that sentence :laughing: Thank you!

**Comment by jmachowinski** [comment]
@tonynajjar  @jayyoung  Just ignore the windows build error for now, we are cleaning up the build failures from the MSVC bump.

**Comment by sloretz** [comment]
Windows rerun - no connext, building up to rclcpp, testing just rclcpp [Build Status](https://ci.ros2.org/job/ci_windows/27658/)

**Comment by tonynajjar** [comment]
Thank you for the push everyone! Happy freeze
