### PR TITLE
Guard against ParameterNotDeclaredException in parameter service callbacks

### LINKED ISSUE #705: Uncaught exception when setting undeclared parameter
## Bug report

**Required Info:**

- Operating System:
  - OSX (i guess applicable to all)
- Installation type:
  - source
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
```
ros2 run demo_nodes_cpp talker
```
```
ros2 param set talker non-declared-parameter 0.0
```

#### Expected behavior
talker nodes ignores undeclared parameter

#### Actual behavior
talker terminates with uncaught exception

### PR DESCRIPTION
**Pull request by jacobperron**
Fixes #705.

If the set_parameters() call fails, it's nice to be able to return a partial result.
Since there is no convenient method to obtain a partial result, we call set_parameters()
once for each parameter.

### CODE REVIEW

**Comment by jacobperron** [comment]
Working on adding test coverage to the existing parameter service tests in `test_rclcpp`.

**Comment by jacobperron** [comment]
With tests in https://github.com/ros2/system_tests/pull/366:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7082/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3309/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5804/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6897/)

File: rclcpp/src/rclcpp/parameter_service.cpp [hunk 1]
```diff
@@ -96,8 +107,15 @@ ParameterService::ParameterService(
...
-      auto result = node_params->set_parameters_atomically(pvariants);
-      response->result = result;
+      try {
+        auto result = node_params->set_parameters_atomically(pvariants);
+        response->result = result;
+      } catch (const rclcpp::exceptions::ParameterNotDeclaredException & ex) {
+        RCLCPP_WARN(
+          rclcpp::get_logger("rclcpp"), "Failed to set parameters atomically: %s", ex.what());
+        response->result.successful = false;
+        response->result.reason = "One or more parameters was not declared before setting";
```
Comment (jubeira) [inline rclcpp/src/rclcpp/parameter_service.cpp]:
```suggestion
        response->result.reason = "One or more parameters were not declared before being set.";
```

File: rclcpp/src/rclcpp/parameter_service.cpp [hunk 2]
```diff
@@ -73,12 +77,19 @@ ParameterService::ParameterService(
...
       std::shared_ptr<rcl_interfaces::srv::SetParameters::Response> response)
     {
-      std::vector<rclcpp::Parameter> pvariants;
+      // Set parameters one-by-one, since there's no way to return a partial result if
+      // set_parameters() fails.
+      auto result = rcl_interfaces::msg::SetParametersResult();
       for (auto & p : request->parameters) {
-        pvariants.push_back(rclcpp::Parameter::from_parameter_msg(p));
+        try {
+          result = node_params->set_parameters({rclcpp::Parameter::from_parameter_msg(p)})[0];
```
Comment (jubeira) [inline rclcpp/src/rclcpp/parameter_service.cpp]: Since you are calling them one by one, I'd consider calling `set_parameters_atomically` (if it's more efficient to do so).

Comment (jacobperron) [reply rclcpp/src/rclcpp/parameter_service.cpp]: Makes sense. Updated 6b9e9de

File: rclcpp/src/rclcpp/parameter_service.cpp (hunk 1 above)
Comment (jacobperron) [reply rclcpp/src/rclcpp/parameter_service.cpp]: Fixed 49cfa7f

**Comment by jacobperron** [comment]
Thanks for the reviews! I'm running tests (which also need review) in https://github.com/ros2/system_tests/pull/366#issuecomment-492790980

File: rclcpp/src/rclcpp/parameter_service.cpp [hunk 3]
```diff
@@ -73,12 +77,19 @@ ParameterService::ParameterService(
...
+        } catch (const rclcpp::exceptions::ParameterNotDeclaredException & ex) {
+          RCLCPP_WARN(rclcpp::get_logger("rclcpp"), "Failed to set parameter: %s", ex.what());
```
[the remark this answers is not in the document]
Comment (jacobperron) [reply rclcpp/src/rclcpp/parameter_service.cpp]: I wasn't sure where to get a reference to it. `ParameterService` only has handles to the following interfaces:

* NodeBaseInterface
* NodeServicesInterface
* NodeParametersInterface
