### PR TITLE
Executor strong reference fix

### LINKED ISSUE #2678: Subscriber is being held when another subscriber callback is being called
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 24.04 (docker and host)
- Installation type:
  - binaries
- Version or commit hash:
  - jazzy
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

```cpp
#include <rclcpp/rclcpp.hpp>

#include <std_msgs/msg/empty.hpp>

class MyClass {
  public:
    MyClass(rclcpp::Node& node) {
        std::cout << "Constructor: " << this << std::endl;

        _sub = node.create_subscription<std_msgs::msg::Empty>("test", 10, std::bind(&MyClass::callback, this, std::placeholders::_1));
    }

    ~MyClass() {
        std::cout << "Destructor:  " << this << ", Count: " << _sub.use_count() << std::endl;
    }

    void callback(const std_msgs::msg::Empty&) {
        std::cout << "Callback:    " << this << std::endl;
        my_data += 1.0;
    } 

  private:
  rclcpp::Subscription<std_msgs::msg::Empty>::SharedPtr _sub;

  double my_data;
};

int main(int argc, char* argv[]) {
    rclcpp::init(argc, argv);
    
    auto node = std::make_shared<rclcpp::Node>("test_node");

    std::unique_ptr<MyClass> object;
    
    auto sub = node->create_subscription<std_msgs::msg::Empty>("sub", 10, [&object, &node](const std_msgs::msg::Empty&){
        if(object){
            object.reset();
        }
        else {
            object = std::make_unique<MyClass>(*node);
        }
    });

    rclcpp::spin(node);

    rclcpp::shutdown();
    
    return 0;
}
```

You should be able to build the executable with just `rclcpp` and `std_msgs` linked.

I recommend compiling with the address sanitizer to make sure it crashes once the issue occurs. Without it, it might not crash but it's definitely UB.
```sh
colcon build --cmake-args -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-fsanitize=address
```

In three terminals

```sh
# Term1
ros2 topic pub --rate 10.0 /sub std_msgs/msg/Empty '{}'
# Term2
ros2 topic pub --rate 100.1 /test std_msgs/msg/Empty '{}'
# Term3
ASAN_OPTIONS=new_delete_type_mismatch=0 ros2 run YOUR_TEST_PACKAGE YOU_TEST_EXECUTABLE
```

#### Expected behavior

My understanding was that the executor had weak ownership of the subscriber and would only get a shared_ptr when executing the callback. Hence, in a single threaded context when a callback from one subscriber is called it should be possible to destroy another subscriber and clean related objects.

Even in a multi threaded context I would expect the same if the two subscribers interacting with each other are part a mutually exclusive callback group.

#### Actual behavior

Here when the callback for `/sub` is called `MyClass` is destroyed but the subscriber to `/test` it contains is held by someone else (the count of the share_ptr is 2).

This worked fine with ROS2 humble, the subscriber count was 1 when it's callback wasn't being called.

Assuming this is the intended behavior it becomes difficult cleanup objects used by subscribers (or containing subscribers as in the example). I'm sure it still feasible by keeping a weak_ptr before resting our shared_ptr, then the executor will hopefully release its shared_ptr and only after that destroy the object. But what was as simple as destroying the object becomes more convoluted.

#### Additional information

I found these issues that are somewhat related but I think it's a different issue since they had callbacks called in parallel which is not the case here:
- https://github.com/ros-navigation/navigation2/issues/4166#issuecomment-1988937428
- https://github.com/ros2/rclcpp/issues/2447

### PR DESCRIPTION
**Pull request by jmachowinski**
fixes https://github.com/ros2/rclcpp/issues/2678

@mjcarroll we should merge this ASAP and backport to jazzy, to keep the ABI breakage to one release

### CODE REVIEW

**Comment by jmachowinski** [comment]
Pulls: ros2/rclcpp#2745
Gist: https://gist.githubusercontent.com/jmachowinski/3a04e1e78a56e9e964d4ae0ac2ae01fc/raw/ddfb92e12cf7c0ce9b6ecc81882b328e6034df2b/ros2.repos
BUILD args: 
TEST args: 
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15193
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22532/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16779/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/2052/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23323/)

**Review by mjcarroll — APPROVED** [review]

File: rclcpp/include/rclcpp/wait_result.hpp [hunk 1]
```diff
@@ -176,7 +176,9 @@ class WaitResult final
       for (; ii < wait_set.size_of_timers(); ++ii) {
         if (rcl_wait_set.timers[ii] != nullptr) {
           ret = wait_set.timers(ii);
-          break;
+          if(ret) {
+            break;
+          }
```
Comment (christophebedard) [inline rclcpp/include/rclcpp/wait_result.hpp]:
```suggestion
          if (ret) {
            break;
          }
```

File: rclcpp/include/rclcpp/wait_result.hpp [hunk 2]
```diff
@@ -217,7 +219,9 @@ class WaitResult final
         if (rcl_wait_set.subscriptions[ii] != nullptr) {
           ret = wait_set.subscriptions(ii);
           rcl_wait_set.subscriptions[ii] = nullptr;
-          break;
+          if(ret) {
+            break;
+          }
```
Comment (christophebedard) [inline rclcpp/include/rclcpp/wait_result.hpp]:
```suggestion
          if (ret) {
            break;
          }
```

File: rclcpp/include/rclcpp/wait_result.hpp [hunk 3]
```diff
@@ -237,7 +241,9 @@ class WaitResult final
         if (rcl_wait_set.services[ii] != nullptr) {
           ret = wait_set.services(ii);
           rcl_wait_set.services[ii] = nullptr;
-          break;
+          if(ret) {
+            break;
+          }
```
Comment (christophebedard) [inline rclcpp/include/rclcpp/wait_result.hpp]:
```suggestion
          if (ret) {
            break;
          }
```

File: rclcpp/include/rclcpp/wait_result.hpp [hunk 4]
```diff
@@ -257,7 +263,9 @@ class WaitResult final
         if (rcl_wait_set.clients[ii] != nullptr) {
           ret = wait_set.clients(ii);
           rcl_wait_set.clients[ii] = nullptr;
-          break;
+          if(ret) {
+            break;
+          }
```
Comment (christophebedard) [inline rclcpp/include/rclcpp/wait_result.hpp]:
```suggestion
          if (ret) {
            break;
          }
```

File: rclcpp/test/rclcpp/executors/test_executors.cpp [hunk 5]
```diff
@@ -1099,3 +1099,61 @@ TYPED_TEST(TestExecutors, dropSomeNodesWithSubscription)
...
+        sub2_works = true;
+        // delete the other subscriber
+        sub1.reset();
+  });
+
+  auto pub = node->create_publisher<test_msgs::msg::Empty>("/test_drop", 10);
+
+  // wait for both subs to be connected
+  auto max_end_time = std::chrono::steady_clock::now() + std::chrono::milliseconds(1500);
+  while((sub1->get_publisher_count() == 0) || (sub2->get_publisher_count() == 0)) {
```
Comment (christophebedard) [inline rclcpp/test/rclcpp/executors/test_executors.cpp]:
```suggestion
  while ((sub1->get_publisher_count() == 0) || (sub2->get_publisher_count() == 0)) {
```

File: rclcpp/test/rclcpp/executors/test_executors.cpp [hunk 6]
```diff
@@ -1099,3 +1099,61 @@ TYPED_TEST(TestExecutors, dropSomeNodesWithSubscription)
...
+    const auto cur_time = std::chrono::steady_clock::now();
+    ASSERT_LT(cur_time, max_end_time);
+  }
+
+  executor.add_node(node);
+
+  // publish some messages, until one subscriber fired. As both subscribers are
+  // connected to the same topic, they should fire in the same wait.
+  max_end_time = std::chrono::steady_clock::now() + std::chrono::milliseconds(100);
+  while(!sub1_works && !sub2_works) {
```
Comment (christophebedard) [inline rclcpp/test/rclcpp/executors/test_executors.cpp]:
```suggestion
  while (!sub1_works && !sub2_works) {
```

**Review by wjwwood — APPROVED** [review]
lgtm with style fixups

But, I do not believe it fixes https://github.com/ros2/rclcpp/issues/2678, it simply makes it less likely (at least for the multi-threaded executor case or two separate executor case). If async `.reset()` happens after the executor has acquired the lock, but before it starts executing the callback then you'll still potentially get into a callback after the "owning" class was reset, thus you still need to capture a weak_ptr in the callback.

The right answer to https://github.com/ros2/rclcpp/issues/2678 is documentation, imo.

This pr is still worth doing because it frees up resources more quickly, but it doesn't solve the original problem completely.

File: rclcpp/test/rclcpp/executors/test_executors.cpp [hunk 7]
```diff
@@ -1099,3 +1099,61 @@ TYPED_TEST(TestExecutors, dropSomeNodesWithSubscription)
 
   ASSERT_TRUE(sub1_works);
 }
+
+TYPED_TEST(TestExecutors, dropSubscriptionDuringCallback)
+{
+  using ExecutorType = TypeParam;
+  ExecutorType executor;
+
+  auto node = std::make_shared<rclcpp::Node>("test_node");
```
Comment (fujitatomoya) [inline rclcpp/test/rclcpp/executors/test_executors.cpp:1109]: i think this test is only assumed to succeed with `CallbackGroupType::MutuallyExclusive` that is current default? i would explicitly add that to the node option to avoid failure in the future.

**Comment by mjcarroll** [comment]
@marcoag FYI we want to get this backported to Jazzy and it does end up with an ABI break.

I think it's important enough to get in, though. Let's coordinate that this gets in before the next sync.

**Review by fujitatomoya — APPROVED** [review]
lgtm with green CI. just a minor comment.

**Review by alsora — APPROVED** [review]

File: rclcpp/include/rclcpp/wait_result.hpp (hunk 1 above)
Comment (jmachowinski) [reply rclcpp/include/rclcpp/wait_result.hpp]: fixed

File: rclcpp/include/rclcpp/wait_result.hpp (hunk 3 above)
Comment (jmachowinski) [reply rclcpp/include/rclcpp/wait_result.hpp]: fixed

File: rclcpp/include/rclcpp/wait_result.hpp (hunk 4 above)
Comment (jmachowinski) [reply rclcpp/include/rclcpp/wait_result.hpp]: fixed

File: rclcpp/test/rclcpp/executors/test_executors.cpp (hunk 5 above)
Comment (jmachowinski) [reply rclcpp/test/rclcpp/executors/test_executors.cpp]: fixed

File: rclcpp/test/rclcpp/executors/test_executors.cpp (hunk 6 above)
Comment (jmachowinski) [reply rclcpp/test/rclcpp/executors/test_executors.cpp]: fixed

File: rclcpp/test/rclcpp/executors/test_executors.cpp (hunk 7 above)
Comment (jmachowinski) [reply rclcpp/test/rclcpp/executors/test_executors.cpp:1109]: I don't see that ever change, but modified the test anyway...

**Comment by jmachowinski** [comment]
Pulls: ros2/rclcpp#2745
Gist: https://gist.githubusercontent.com/jmachowinski/b0a8898b10d9d067c61f5b40f4940d9b/raw/ddfb92e12cf7c0ce9b6ecc81882b328e6034df2b/ros2.repos
BUILD args: 
TEST args: 
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15204
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22546/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16790/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/2063/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23336/)

**Comment by marcoag** [comment]
https://github.com/Mergifyio backport jazzy
