### PR TITLE
use std::recursive_mutex for action requests.

### LINKED ISSUE #2796: async_send_goal deadlocks
### Operating System:

Ubuntu 24.04

### ROS version or commit hash:

jazzy

### RMW implementation (if applicable):

rmw_cyclonedds_cpp (also on rmw_zenoh_cpp)

### RMW Configuration (if applicable):

_No response_

### Client library (if applicable):

rclcpp

### 'ros2 doctor --report' output

_No response_

### Steps to reproduce issue

Inconsistent

### Expected behavior

async_send_goal always returns a future without blocking

### Actual behavior

async_send_goal deadlocks

### Additional information

I don't know enough of the internals of action clients to know if this is a bug or not.
The setup is an action server and action client (part of many other nodes in my launch setup), both using the SingleThreadedExecutor. They happily work together and callbacks for the actions are received. But once in a while, the async_send_goal gets deadlocked. I still see the log statements of the action server completing the previous actions, but the corresponding log statements for the callbacks in the action client are never printed, as the SingleThreadedExecutor never gets to processing these as it gets stuck on the async_send_goal call.

I guess the first question is whether I'm reporting a bug or whether this is just me not understanding what should happen. Should it by design be theoretically impossible for an async_send_goal to deadlock when using a SingleThreadedExecutor? That was my understanding, but I might be wrong on that.

Deadlocked stack trace:
```
libc.so.6!futex_wait(int private, unsigned int expected, unsigned int * futex_word) (futex-internal.h:146)
libc.so.6!__GI___lll_lock_wait(int * futex, int * futex@entry, int private) (lowlevellock.c:49)
libc.so.6!lll_mutex_lock_optimized(pthread_mutex_t * mutex) (pthread_mutex_lock.c:48)
libc.so.6!___pthread_mutex_lock(pthread_mutex_t * mutex) (pthread_mutex_lock.c:93)
librclcpp_action.so!rclcpp_action::ClientBase::send_goal_request(std::shared_ptr<void>, std::function<void (std::shared_ptr<void>)>) (Unknown Source:0)
rclcpp_action::Client<zeal_msgs::action::Move>::async_send_goal(class rclcpp_action::Client<zeal_msgs::action::Move> * const this, const rclcpp_action::Client<zeal_msgs::action::Move>::Goal & goal, const struct rclcpp_action::Client<zeal_msgs::action::Move>::SendGoalOptions & options) (/opt/ros/jazzy/include/rclcpp_action/rclcpp_action/client.hpp:441)
ZealPlanner::NavigateToPoseActionServer::processQueue(class ZealPlanner::NavigateToPoseActionServer * const this) (/ament/overlay_ws/src/zeal_picker/zeal_planner/src/navigate_to_pose_action_server.cpp:257)
ZealPlanner::NavigateToPoseActionServer::processQueue()::{lambda(std::shared_ptr<rclcpp_action::ClientGoalHandle<zeal_msgs::action::Move> > const&)#1}::operator()(std::shared_ptr<rclcpp_action::ClientGoalHandle<zeal_msgs::action::Move> > const&) const(const struct {...} * const __closure, const rclcpp_action::ClientGoalHandle<zeal_msgs::action::Move>::SharedPtr & handle) (/ament/overlay_ws/src/zeal_picker/zeal_planner/src/navigate_to_pose_action_server.cpp:201)
std::__invoke_impl<void, ZealPlanner::NavigateToPoseActionServer::processQueue()::{lambda(std::shared_ptr<rclcpp_action::ClientGoalHandle<zeal_msgs::action::Move> > const&)#1}&, std::shared_ptr<rclcpp_action::ClientGoalHandle<zeal_msgs::action::Move> > >(std::__invoke_other, ZealPlanner::NavigateToPoseActionServer::processQueue()::{lambda(std::shared_ptr<rclcpp_action::ClientGoalHandle<zeal_msgs::action::Move> > const&)#1}&, std::shared_ptr<rclcpp_action::ClientGoalHandle<zeal_msgs::action::Move> >&&)(struct {...} & __f) (/usr/include/c++/13/bits/invoke.h:61)
std::__invoke_r<void, ZealPlanner::NavigateToPoseActionServer::processQueue()::{lambda(std::shared_ptr<rclcpp_action::ClientGoalHandle<zeal_msgs::action::Move> > const&)#1}&, std::shared_ptr<rclcpp_action::ClientGoalHandle<zeal_msgs::action::Move> > >(ZealPlanner::NavigateToPoseActionServer::processQueue()::{lambda(std::shared_ptr<rclcpp_action::ClientGoalHandle<zeal_msgs::action::Move> > const&)#1}&, std::shared_ptr<rclcpp_action::ClientGoalHandle<zeal_msgs::action::Move> >&&)(struct {...} & __fn) (/usr/include/c++/13/bits/invoke.h:111)
std::_Function_handler<void (std::shared_ptr<rclcpp_action::ClientGoalHandle<zeal_msgs::action::Move> >), ZealPlanner::NavigateToPoseActionServer::processQueue()::{lambda(std::shared_ptr<rclcpp_action::ClientGoalHandle<zeal_msgs::action::Move> > const&)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<rclcpp_action::ClientGoalHandle<zeal_msgs::action::Move> >&&)(const union std::_Any_data & __functor, class std::shared_ptr<rclcpp_action::ClientGoalHandle<zeal_msgs::action::Move> > && __args#0) (/usr/include/c++/13/bits/std_function.h:290)
std::function<void (std::shared_ptr<rclcpp_action::ClientGoalHandle<zeal_msgs::action::Move> >)>::operator()(std::shared_ptr<rclcpp_action::ClientGoalHandle<zeal_msgs::action::Move> >) const(const class std::function<void(std::shared_ptr<rclcpp_action::ClientGoalHandle<zeal_msgs::action::Move> >)> * const this, class std::shared_ptr<rclcpp_action::ClientGoalHandle<zeal_msgs::action::Move> > __args#0) (/usr/include/c++/13/bits/std_function.h:591)
rclcpp_action::Client<zeal_msgs::action::Move>::async_send_goal(zeal_msgs::action::Move_Goal_<std::allocator<void> > const&, rclcpp_action::Client<zeal_msgs::action::Move>::SendGoalOptions const&)::{lambda(std::shared_ptr<void>)#1}::operator()(std::shared_ptr<void>)(struct {...} * const __closure, class std::shared_ptr<void> response) (/opt/ros/jazzy/include/rclcpp_action/rclcpp_action/client.hpp:466)
std::__invoke_impl<void, rclcpp_action::Client<zeal_msgs::action::Move>::async_send_goal(zeal_msgs::action::Move_Goal_<std::allocator<void> > const&, rclcpp_action::Client<zeal_msgs::action::Move>::SendGoalOptions const&)::{lambda(std::shared_ptr<void>)#1}&, std::shared_ptr<void> >(std::__invoke_other, rclcpp_action::Client<zeal_msgs::action::Move>::async_send_goal(zeal_msgs::action::Move_Goal_<std::allocator<void> > const&, rclcpp_action::Client<zeal_msgs::action::Move>::SendGoalOptions const&)::{lambda(std::shared_ptr<void>)#1}&, std::shared_ptr<void>&&)(struct {...} & __f) (/usr/include/c++/13/bits/invoke.h:61)
std::__invoke_r<void, rclcpp_action::Client<zeal_msgs::action::Move>::async_send_goal(zeal_msgs::action::Move_Goal_<std::allocator<void> > const&, rclcpp_action::Client<zeal_msgs::action::Move>::SendGoalOptions const&)::{lambda(std::shared_ptr<void>)#1}&, std::shared_ptr<void> >(rclcpp_action::Client<zeal_msgs::action::Move>::async_send_goal(zeal_msgs::action::Move_Goal_<std::allocator<void> > const&, rclcpp_action::Client<zeal_msgs::action::Move>::SendGoalOptions const&)::{lambda(std::shared_ptr<void>)#1}&, std::shared_ptr<void>&&)(struct {...} & __fn) (/usr/include/c++/13/bits/invoke.h:111)
std::_Function_handler<void (std::shared_ptr<void>), rclcpp_action::Client<zeal_msgs::action::Move>::async_send_goal(zeal_msgs::action::Move_Goal_<std::allocator<void> > const&, rclcpp_action::Client<zeal_msgs::action::Move>::SendGoalOptions const&)::{lambda(std::shared_ptr<void>)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<void>&&)(const union std::_Any_data & __functor, class std::shared_ptr<void> && __args#0) (/usr/include/c++/13/bits/std_function.h:290)
librclcpp_action.so!rclcpp_action::ClientBase::handle_goal_response(rmw_request_id_s const&, std::shared_ptr<void>) (Unknown Source:0)
librclcpp_action.so!rclcpp_action::ClientBase::execute(std::shared_ptr<void> const&) (Unknown Source:0)
librclcpp.so!rclcpp::Executor::execute_any_executable(rclcpp::AnyExecutable&) (Unknown Source:0)
librclcpp.so!rclcpp::executors::SingleThreadedExecutor::spin() (Unknown Source:0)
```

### PR DESCRIPTION
**Pull request by fujitatomoya**
closes https://github.com/ros2/rclcpp/issues/2796

> [!NOTE]
> This is kind of behavior change, so not planning to backport.

### CODE REVIEW

File: rclcpp_action/src/client_base.cpp [hunk 1]
```diff
@@ -399,7 +399,7 @@ ClientBase::handle_goal_response(
 void
 ClientBase::send_goal_request(std::shared_ptr<void> request, ResponseCallback callback)
 {
-  std::unique_lock<std::mutex> guard(pimpl_->goal_requests_mutex);
+  std::lock_guard<std::recursive_mutex> guard(pimpl_->goal_requests_mutex);
```
Comment (fujitatomoya) [inline rclcpp_action/src/client_base.cpp:402]: i do not find the reason why it needs to be `std::unique_lock` here.

File: rclcpp_action/src/client_base.cpp [hunk 2]
```diff
@@ -386,7 +386,7 @@ ClientBase::handle_goal_response(
   const rmw_request_id_t & response_header,
   std::shared_ptr<void> response)
 {
-  std::lock_guard<std::mutex> guard(pimpl_->goal_requests_mutex);
+  std::lock_guard<std::recursive_mutex> guard(pimpl_->goal_requests_mutex);
```
Comment (fujitatomoya) [inline rclcpp_action/src/client_base.cpp:389]: this allows us to request another goal to the action server on previous goal response (accept or reject) is arrived.

File: rclcpp_action/src/client_base.cpp (hunk 1 above)
Comment (jmachowinski) [reply rclcpp_action/src/client_base.cpp:402]: should make no difference, this constructor of unique_lock would lock on construction and unlock on destruction.

**Review by jmachowinski — APPROVED** [review]

**Comment by ahcorde** [comment]
Pulls: ros2/rclcpp#2798
Gist: https://gist.githubusercontent.com/ahcorde/c1b5f9f03cd40336d5579a2996d5ad60/raw/129c5a5d192988f857b54529c200817a88799ff2/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp
TEST args:  --packages-above rclcpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15654
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/23119/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/17328/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/2591/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23986/)
